Build script for lego golang package
ppc64le/build-scripts pull request #1087
Opened 2021-10-07 16:04 UTC by ezeeyahoo

Hi

Please review and provide your feeback.

Thanks

2021-10-08 13:24 UTC, amitsadaphule requested changes

2021-10-08 13:24 UTC, amitsadaphule commented on l/lego/lego_ubi8.3.sh
> +
I think there's no need to add things to `.profile` etc and complicate the `go` installation steps. Please refer to [this](https://github.com/ppc64le/build-scripts/commit/49ae79e15cd863475fb705a204293982fe3e95bb#diff-4ba2744d2c13d2a179b0ee4edbb7a701da7697a167fd13f1ff8c9084d4e44353R23-R29)

2021-10-08 13:24 UTC, amitsadaphule commented on l/lego/lego_ubi8.3.sh
> +[ $? != 0 ] && exit 1
`set -eu` can be used at the beginning of the script to get rid of these command status checks.

2021-10-12 14:33 UTC, amitsadaphule commented on l/lego/lego_ubi8.3.sh
> +# Disclaimer: This script has been tested both in root and user mode on given
To keep it simple, we can simply have this script run as root user. Being a _go_ package, it's not necessary to have a capability to run as non-root.

2021-10-12 14:43 UTC, amitsadaphule commented on l/lego/lego_ubi8.3.sh
> +
We can simply get rid of these writes to .profile/.bashrc/... We're running the script in a UBI container and it is ok to assume that the script will be run in a fresh container.

2021-12-03 04:28 UTC, Siddhesh-Ghadi commented
This PR can be closed in favor of #1221.

2021-12-03 13:15 UTC, closed without merging