Create archiver_ubi_8.4.sh
ppc64le/build-scripts pull request #1118
Opened 2021-10-20 15:49 UTC by nageshlop

Verified build and test of archiver package on ppc64le with master (v3.5.0) and v3.2.0 as updated in the spread sheet.

2021-10-21 06:15 UTC, gururajrkatti commented
@ezeeyahoo can you pl. review

2021-11-02 07:37 UTC, nageshlop commented
Hi @ezeeyahoo, Could you let me know if there are any changes required or good to proceed?

2021-12-02 15:16 UTC, Siddhesh-Ghadi commented
Script looks good to me. Can we merge it? @kandarpamalipeddi

2021-12-02 15:36 UTC, kandarpamalipeddi requested changes

2021-12-02 15:36 UTC, kandarpamalipeddi commented on a/archiver/archiver_ubi_8.4.sh
> +fi
Please use either `v3.5.0` or `v3.2.0` instead of master.

2021-12-02 15:36 UTC, kandarpamalipeddi commented on a/archiver/archiver_ubi_8.4.sh
> +git clone https://github.com/mholt/archiver
It would be really good, if this is cloned to GOPATH.

2022-01-10 08:52 UTC, closed without merging