adding build script for org.osgi
ppc64le/build-scripts pull request #1192
Opened 2021-11-23 07:37 UTC by Manik-ibm

2021-11-24 08:23 UTC, snehlatamohite approved these changes

2021-11-24 08:24 UTC, snehlatamohite requested changes
Script name has to be org.osgi_UBI_8.0.sh  OR org.osgi_UBI_8.3.sh  ? I assume package ported on BI 8.3?

2021-11-24 14:01 UTC, Manik-ibm commented
script file name renamed: org.osgi_UBI_8.0.sh -> org.osgi_UBI_8.4.sh

2021-12-24 10:10 UTC, seth-priya commented
@snehlatamohite are we good to move fwd. here?

2022-01-06 15:37 UTC, merged