buildscript for libtrust version v0.0.0-20160708172513-aabc10ec26b7
ppc64le/build-scripts pull request #1193
Opened 2021-11-23 12:12 UTC by Sapana-Khemkar

verified libtrust version v0.0.0-20160708172513-aabc10ec26b7 for ubi8.4

2021-11-24 08:43 UTC, seth-priya commented
@kandarpamalipeddi please review

2021-11-25 15:39 UTC, kandarpamalipeddi requested changes
Please add a LICENSE File along with the script.

2021-11-25 15:45 UTC, kandarpamalipeddi commented on l/libtrust/libtrust_ubi_8.4.sh
> +# Source repo    :
Mention Version as : commit id
Source repo as well.

2021-11-25 15:46 UTC, kandarpamalipeddi commented on l/libtrust/libtrust_ubi_8.4.sh
> +PACKAGE_COMMIT_HASH=${PACKAGE_VERSION_SPLIT[2]}
Can we replace these lines as:
```
PACKAGE_COMMIT_HASH=`echo $PACKAGE_VERSION | cut -d'-' -f3`
```

2021-12-01 10:20 UTC, Sapana-Khemkar commented on l/libtrust/libtrust_ubi_8.4.sh
> +# Source repo    :
done

2021-12-01 10:21 UTC, Sapana-Khemkar commented on l/libtrust/libtrust_ubi_8.4.sh
> +PACKAGE_COMMIT_HASH=${PACKAGE_VERSION_SPLIT[2]}
done

2021-12-01 16:58 UTC, kandarpamalipeddi approved these changes

2021-12-01 16:58 UTC, merged