metrics-server v0.3.2 build script for ubi 8.4
ppc64le/build-scripts pull request #1202
Opened 2021-11-25 09:01 UTC by Sapana-Khemkar

metrics-server v0.3.2 build script for ubi 8.4

2021-11-26 09:23 UTC, seth-priya commented
@pratham-m please review.

2022-01-17 11:35 UTC, kandarpamalipeddi requested changes

2022-01-17 11:35 UTC, kandarpamalipeddi commented on m/metrics-server/metrics-server_ubi_8.4.sh
> +# Source repo    :
Please update the header as per latest script guidelines.

2022-01-17 11:35 UTC, kandarpamalipeddi commented on m/metrics-server/metrics-server_ubi_8.4.sh
> +#!/bin/bash
Use  `#!/bin/bash -e`

2022-01-17 11:35 UTC, kandarpamalipeddi commented on m/metrics-server/metrics-server_ubi_8.4.sh
> +export GOPATH=/home/tester/go
Use 
`export GOPATH=$(go env GOPATH)`  or create the `/home/tester/go` path before using it.

2022-02-04 03:45 UTC, seth-priya approved these changes

2022-02-04 03:45 UTC, merged