Added build script for kafka-python
ppc64le/build-scripts pull request #1209
Opened 2021-11-26 14:09 UTC by atharv-phadnis

Package Name: **kafka-python**
Package Version: **2.0.2**
Package URL: [kafka-python](https://github.com/dpkp/kafka-python)

Tested on: **UBI 8.5**
Build Errors: **None**
Test Errors: **None**

2021-11-30 11:48 UTC, seth-priya commented
@Ryan-Dmello please review

2021-11-30 15:11 UTC, Ryan-Dmello requested changes
@atharv-phadnis other than the comment I mentioned, build script looks ok to me

2021-11-30 15:11 UTC, Ryan-Dmello commented on k/kafka-python/kafka-python_ubi_8.5.sh
> +	echo "------------------$PACKAGE_NAME:install_or_test_fails---------------------"
Tox command is going to perform package testing only. Please refer file tox.ini for details.

For installation use following command, after line 45:

`pip3 install ./`

Please update the wordings, after adding installation command.

2021-11-30 15:13 UTC, Ryan-Dmello commented on k/kafka-python/kafka-python_ubi_8.5.sh
> +	echo "------------------$PACKAGE_NAME:install_or_test_fails---------------------"
Also package is installable via pip3 command. 
`pip3 install kafka-python`

Please check if build script is actually required

2021-11-30 16:06 UTC, atharv-phadnis commented
@Ryan-Dmello Made the required changes, please have a look at the script.

Was getting random test errors using `pip3 install .`, so went with the classic `python3 setup.py install`.

2021-12-01 05:14 UTC, Ryan-Dmello commented
Latest changes looks ok

2021-12-01 06:20 UTC, Ryan-Dmello approved these changes

2021-12-03 13:20 UTC, merged