Add build script for package php-encryption: v2.2.1
ppc64le/build-scripts pull request #1298
Opened 2021-12-23 11:05 UTC by vedang-wartikar

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2022-01-05 09:21 UTC, seth-priya commented
@Ryan-Dmello please review

2022-01-05 10:23 UTC, Ryan-Dmello requested changes
Other than comments related to file name not matching distro information, changes looks ok

2022-01-05 10:23 UTC, Ryan-Dmello commented on p/php-encryption/php-encryption_ubi8.sh
> +# Tested on	: RHEL 8.3
Distro information is not matching with file name

2022-01-05 10:23 UTC, Ryan-Dmello commented on p/phpunit/phpunit_ubi8.sh
> +# Tested on	: RHEL 8.3
Distro information is not matching with file name

2022-01-05 10:23 UTC, Ryan-Dmello commented on s/spdx-licenses/spdx-licenses_ubi8.sh
> +# Tested on	: RHEL 8.3
Distro information is not matching with file name

2022-01-31 10:04 UTC, kandarpamalipeddi approved these changes

2022-01-31 10:04 UTC, merged