Jest
ppc64le/build-scripts pull request #1348
Opened 2022-01-03 12:09 UTC by rajusah15

## Checklist

- [ ] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [ ] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2022-01-17 11:53 UTC, kandarpamalipeddi requested changes
Please remove a/airline/airline_rhel_8.3.sh from this commit.

2022-01-17 11:53 UTC, kandarpamalipeddi commented on j/jest/jest_rhel8.3.sh
> +# Maintainer    : Raju.Sah@ibm.com
Update the header as per Template.

2022-01-17 11:53 UTC, kandarpamalipeddi commented on j/jest/jest_rhel8.3.sh
> +# Version       : 9b9afadbbf7f0cf8f93d72656cba4b3288d0ae49 or tag: 25.2.3
`tag: 25.2.3` is not available.

2022-01-18 03:10 UTC, rajusah15 commented
Will raise another PR as some unwanted file has uploaded and also follow the new template.

2022-01-18 03:10 UTC, closed without merging