Codemirror graphql
ppc64le/build-scripts pull request #1353
Opened 2022-01-03 13:23 UTC by rajusah15

## Checklist

- [ ] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [ ] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2022-01-17 16:41 UTC, kandarpamalipeddi requested changes
Please remove a/airline/airline_rhel_8.3.sh in this pull request.

2022-01-17 16:41 UTC, kandarpamalipeddi commented on c/codemirror-graphql/codemirror-graphql_rhel_8.3.sh
> +#
Please updated header as per the template.

2022-01-17 16:41 UTC, kandarpamalipeddi commented on c/codemirror-graphql/codemirror-graphql_rhel_8.3.sh
> +#export the path
Remove this comment.

2022-01-18 03:03 UTC, rajusah15 commented
New PR has been raised for this package , so i am closing this one.

2022-01-18 03:03 UTC, closed without merging