buildscript
ppc64le/build-scripts pull request #1409
Opened 2022-01-07 10:30 UTC by rajusah15

## Checklist

- [ ] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [ ] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2022-01-07 12:10 UTC, seth-priya commented
@rajusah15 always mention the name of the package in the title of the PR, something like "Build script for <Package Name> for <Distro Name> <Distro Version>. You can also optionally add the package version if the script name has it (that is if the script is very specific to a version)

2022-01-07 12:38 UTC, rajusah15 commented
> 

Noted.

2022-01-07 15:43 UTC, kandarpamalipeddi requested changes

2022-01-07 15:43 UTC, kandarpamalipeddi commented on r/remarkable/remarkable_ubi_8.3.sh
> +yum install -y git npm
By default, yum installs node 10.
Please use the node 12 for build and validations.

2022-01-10 07:04 UTC, kandarpamalipeddi commented
Closing this PR, as it is renaming the no-existing file with remarkable script.

2022-01-10 07:04 UTC, closed without merging