adding typescript script for ubi 8.3
ppc64le/build-scripts pull request #1420
Opened 2022-01-10 13:46 UTC by adilhusain-s

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2022-01-10 16:00 UTC, seth-priya commented on t/typescript/typescript_3.9.9_ubi_8.3.sh
> +#
@adilhusain-s We have recently added some additional fields here like Language and Travis-Check, please update/add those, refer to the latest templates at https://github.com/ppc64le/build-scripts/tree/master/templates

2022-01-11 08:27 UTC, Siddhesh-Ghadi requested changes

2022-01-11 08:27 UTC, Siddhesh-Ghadi commented on t/typescript/typescript_3.9.9_ubi_8.3.sh
> +PACKAGE_VERSION="v3.9.9"
Make this configurable from command line.
```suggestion
PACKAGE_VERSION=${1:-v3.9.9}
```

2022-01-13 13:03 UTC, Siddhesh-Ghadi commented
Tests are failing on travis with timeout. Are they passing on local setup? @adilhusain-s 
```
 fourslash test annotateWithTypeFromJSDoc1.ts runs correctly:\n     Error: Timeout of 40000ms exceeded.
```

2022-01-17 06:04 UTC, adilhusain-s commented
yes, the build and tests are successful on local set up inside the container.

2022-01-28 16:56 UTC, merged