Build script for Bugsnag
ppc64le/build-scripts pull request #1432
Opened 2022-01-11 13:14 UTC by Sapana-Khemkar

## Checklist

- [ ] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [ ] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2022-02-04 04:27 UTC, seth-priya requested changes
Please check the reason for the travis build failure

2022-02-04 04:27 UTC, seth-priya commented on b/bugsnag/bugsnag_ubi8.4.sh
> +wget https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official && mv RPM-GPG-KEY-CentOS-Official /etc/pki/rpm-gpg/. && rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-Official
I am not sure this will work now and in any case we need to remove unwanted repos and packages

2022-02-04 04:27 UTC, seth-priya commented on b/bugsnag/bugsnag_ubi8.4.sh
> +set -e
Please update as per latest template

2022-02-04 04:27 UTC, seth-priya commented on b/bugsnag/bugsnag_ubi8.4.sh
> +# Travis-Check  : False
This should be true

2022-02-04 04:27 UTC, seth-priya commented on b/bugsnag/bugsnag_ubi8.4.sh
> +PACKAGE_VERSION=v6.20.0
Please accept version as a parameter

2022-02-08 11:37 UTC, closed without merging

2022-02-08 11:38 UTC, Sapana-Khemkar commented
After implementing review comments test cases are failing and needs more investigation. Hence closing this PR