Added build script for httpmime
ppc64le/build-scripts pull request #1442
Opened 2022-01-12 07:23 UTC by saurabh-gore

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?

Package Name : httpmime
Package Version : rel/v4.1.2
Package URL : [httpmime](https://github.com/apache/httpcomponents-client)

Tested On : UBI 8.5

2022-01-12 15:46 UTC, Siddhesh-Ghadi requested changes
Please squash the commit. Rest all looks good.

2022-01-12 15:47 UTC, Siddhesh-Ghadi commented on h/httpmime/httpmime_ubi_8.5.sh
> +# Tested on		: "Red Hat Enterprise Linux 8.5" (Docker)
Can we change this to UBI?
```suggestion
# Tested on		: UBI 8.5
```

2022-01-13 06:28 UTC, saurabh-gore commented
@Siddhesh-Ghadi Updated , Please review.

2022-01-13 08:25 UTC, Siddhesh-Ghadi approved these changes
LGTM.

2022-01-13 08:33 UTC, merged