Build script for Flog
ppc64le/build-scripts pull request #1486
Opened 2022-01-17 13:41 UTC by Sapana-Khemkar

## Checklist

- [ ] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [ ] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2022-02-04 03:54 UTC, seth-priya requested changes

2022-02-04 03:54 UTC, seth-priya commented on f/flog/flog_ubi_8.4.sh
> +yum-config-manager --add-repo http://mirror.centos.org/centos/8/AppStream/ppc64le/os/ && yum-config-manager --add-repo http://mirror.centos.org/centos/8/PowerTools/ppc64le/os/ && yum-config-manager -
please remove unwanted repositories and packages

2022-02-04 03:54 UTC, seth-priya commented on f/flog/flog_ubi_8.4.sh
> +set -e
Needs update as per new template

2022-02-04 03:54 UTC, seth-priya commented on f/flog/flog_ubi_8.4.sh
> +# Travis-Check  : False
this should be true?

2022-07-25 11:25 UTC, Amit-Sirohi commented
@seth-priya @kandarpamalipeddi can one of you please review this PR. Changes done as per review comments.

2022-07-26 08:19 UTC, kandarpamalipeddi approved these changes

2022-08-08 03:58 UTC, seth-priya approved these changes

2022-08-08 03:58 UTC, merged