Added build script for the node package get-intrinsic
ppc64le/build-scripts pull request #1624
Opened 2022-01-27 14:32 UTC by kumarvikas2020

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2022-01-27 16:08 UTC, kandarpamalipeddi requested changes

2022-01-28 05:48 UTC, kumarvikas2020 commented on g/get-intrinsic/get-intrinsic_ubi_8.5.bash
> +nvm install --latest-npm 10.24
This is a miss and has been corrected.

2022-01-28 05:49 UTC, kumarvikas2020 commented on g/get-intrinsic/get-intrinsic_ubi_8.5.bash
> +set -e
It is removed.

2022-01-28 12:26 UTC, kandarpamalipeddi approved these changes

2022-01-28 12:26 UTC, merged