Added build script for jsbn
ppc64le/build-scripts pull request #1637
Opened 2022-01-28 11:38 UTC by vathsalashetty25

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2022-01-28 13:34 UTC, kandarpamalipeddi requested changes
Tests are failing on Travis job.
Please check the results.

If it is in parity with Intel, please add the failures in the script in comments at end of script.

2022-01-28 13:34 UTC, kandarpamalipeddi commented on j/jsbn/jsbn_ubi_8.5.sh
> +# Tests are not available(Test N/A).
Do we need this comments ?

2022-01-28 13:34 UTC, kandarpamalipeddi commented on j/jsbn/jsbn_ubi_8.5.sh
> +# run the test command from test.sh
There is not test.sh file in this repo.
Looks like this comment is not needed.

2022-01-31 13:18 UTC, vathsalashetty25 commented on j/jsbn/jsbn_ubi_8.5.sh
> +# Tests are not available(Test N/A).
Updated script with required changes

2022-02-02 09:33 UTC, kandarpamalipeddi approved these changes

2022-02-02 09:33 UTC, merged