added build script for mathutil go package
ppc64le/build-scripts pull request #1927
Opened 2022-03-31 03:21 UTC by amitmukati-2604

## Checklist

- [ ] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [ ] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2022-04-05 16:58 UTC, kandarpamalipeddi requested changes

2022-04-05 16:58 UTC, kandarpamalipeddi commented on m/mathutil/mathutil_ubi8.5.sh
> +# Travis-Check  : True
Looks like, Test execution is taking more than 40 mins.
Can you please run the tests on VM and update the status in comments at the end of the script ?

2022-06-24 10:17 UTC, seth-priya commented
@kandarpamalipeddi can you please confirm this?

2022-06-27 04:28 UTC, kandarpamalipeddi approved these changes

2022-06-27 04:28 UTC, merged