added Lit ubi 8.5
ppc64le/build-scripts pull request #2041
Opened 2022-05-11 09:33 UTC by Alston-Dias

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2022-05-13 04:13 UTC, seth-priya commented
@prashantkhoje  please review

2022-05-13 12:38 UTC, prashantkhoje commented on l/lit/Lit_ubi_8.5.sh
> +# Tested on     : UBI 8.3
Script name suggests you used 8.5. Please change accordingly.

2022-05-13 12:38 UTC, prashantkhoje commented on l/lit/Lit_ubi_8.5.sh
> +#!/bin/bash -e
Why is the folder and file named lit*?
Please avoid using capital letters in filename.

2022-05-13 12:38 UTC, prashantkhoje commented on l/lit/Lit_ubi_8.5.sh
> +# Maintainer    : BulkPackageSearch Automation {maintainer}
Please add your name as maintainer.

2022-05-13 12:38 UTC, prashantkhoje commented on l/lit/Lit_ubi_8.5.sh
> +        exit 0
Please use correct indentation.

2022-05-16 08:17 UTC, prashantkhoje commented on l/lit/Lit_ubi_8.5.sh
> +#!/bin/bash -e
Named as lit because, script focuses only on lit from llvm-project.

2022-05-16 08:18 UTC, prashantkhoje approved these changes
LGTM

2022-05-16 09:48 UTC, seth-priya requested changes

2022-05-16 09:48 UTC, seth-priya commented on l/lit/lit_ubi_8.5.sh
> +# Maintainer    : Alston Dias <Vedang.Wartikar@ibm.com>
Please correct the email id

2022-05-16 09:48 UTC, seth-priya commented on l/lit/lit_ubi_8.5.sh
> +# Package       : llvm-project
this is misleading if we are not building the entire llvm-project tree, let's be specific

2022-05-16 09:48 UTC, seth-priya commented on l/lit/lit_ubi_8.5.sh
> +PACKAGE_NAME=llvm-project
let's be specific with the package name if we are not building the entire tree

2022-06-13 04:24 UTC, seth-priya approved these changes

2022-06-13 04:24 UTC, merged