Add build script for jekyll-commonmark: v1.2.0
ppc64le/build-scripts pull request #2101
Opened 2022-05-24 05:49 UTC by shreyakajbaje

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2022-05-26 14:24 UTC, seth-priya requested changes

2022-05-26 14:24 UTC, seth-priya commented on j/jekyll-commonmark/jekyll-commonmark_ubi_8.5.sh
> +# Language      : Node
this is a Ruby package, not Node.js?

2022-05-26 14:24 UTC, seth-priya commented on j/jekyll-commonmark/jekyll-commonmark_ubi_8.5.sh
> +# Script License: MIT License
The Script license should always be Apache 2.0, note that it is not the same as package license

2022-05-26 14:24 UTC, seth-priya commented on j/jekyll-commonmark/jekyll-commonmark_ubi_8.5.sh
> +wget https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.1.tar.gz
we can use rvm to install the required ruby version rather than building it from source? (see the templates folder in this repo for reference)

2022-06-17 04:41 UTC, seth-priya commented
@shreyakajbaje do we know why the travis build is failing?

2022-06-22 05:59 UTC, vedang-wartikar approved these changes
the script has been updated and testcases are passing. looks good to merge @seth-priya

2022-06-22 09:38 UTC, merged