pgtype Version 1.8.0 test and validation script
ppc64le/build-scripts pull request #2157
Opened 2022-06-01 08:05 UTC by ambujkumar3

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2022-07-27 04:35 UTC, seth-priya commented
@prashantkhoje please review

2022-08-03 14:02 UTC, prashantkhoje requested changes
Formatted script

2022-08-03 14:02 UTC, prashantkhoje commented on p/pgtype/pgtype_ubi_8.5.sh
> +echo $PWD
```suggestion
# Check if package exists
if [ -d "$PACKAGE_NAME" ] ; then
    rm -rf $PACKAGE_NAME
    echo "$PACKAGE_NAME  | $PACKAGE_VERSION | $OS_NAME | GitHub | Removed existing package if any"
fi

if ! git clone $PACKAGE_URL $PACKAGE_NAME; then
    echo "------------------$PACKAGE_NAME:clone_fails---------------------------------------"
    echo "$PACKAGE_URL $PACKAGE_NAME"
    echo "$PACKAGE_NAME  |  $PACKAGE_URL |  $PACKAGE_VERSION | $OS_NAME | GitHub | Fail |  Clone_Fails"
    exit 0
fi
cd /home/tester/$PACKAGE_NAME
git checkout $PACKAGE_VERSION

if ! (go build); then
    echo "------------------$PACKAGE_NAME:build failed---------------------"
    echo "$PACKAGE_VERSION $PACKAGE_NAME"
    echo "$PACKAGE_NAME  | $PACKAGE_VERSION | $OS_NAME | GitHub | Fail |  build_Fails"
    exit 1
fi
echo $PWD
```

2022-08-03 14:02 UTC, prashantkhoje commented on p/pgtype/pgtype_ubi_8.5.sh
> +fi
```suggestion

if ! PGX_TEST_DATABASE="host=127.0.0.1 port=5433 database=pgx_test user=pgx_pw password=secret sslmode=disable" go test -v ./...; then
    echo "------------------$PACKAGE_NAME:install_success_but_test_fails---------------------"
    echo "$PACKAGE_URL $PACKAGE_NAME" > /home/tester/output/test_fails
    echo "$PACKAGE_NAME  |  $PACKAGE_URL | $PACKAGE_VERSION | $OS_NAME | GitHub | Fail |  Install_success_but_test_Fails" > /home/tester/output/version_tracker
    exit 1
else
    echo "------------------$PACKAGE_NAME:install_&_test_both_success-------------------------"
    echo "$PACKAGE_VERSION $PACKAGE_NAME" > /home/tester/output/test_success
    echo "$PACKAGE_NAME  |  $PACKAGE_VERSION | $PACKAGE_VERSION | $OS_NAME | GitHub  | Pass |  Both_Install_and_Test_Success" > /home/tester/output/version_tracker
    exit 0
fi
```

2022-08-04 10:00 UTC, prashantkhoje commented
LGTM

2022-08-04 11:13 UTC, merged