pgx Version 4.12.0 test and validation script
ppc64le/build-scripts pull request #2161
Opened 2022-06-01 13:26 UTC by ambujkumar3

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2022-07-27 04:35 UTC, seth-priya commented
@prashantkhoje please review

2022-08-03 13:25 UTC, prashantkhoje requested changes
Minor formatting changes. Otherwise looks good.

2022-08-03 13:25 UTC, prashantkhoje commented on p/pgx/pgx_ubi_8.5.sh
> +
```suggestion

PACKAGE_NAME=pgx
PACKAGE_VERSION=${1:-v4.12.0}
PACKAGE_URL=https://github.com/jackc/pgx.git

dnf install wget git -y
```

2022-08-03 13:25 UTC, prashantkhoje commented on p/pgx/pgx_ubi_8.5.sh
> +fi
```suggestion
if [ -d "postgres" ] ; then
    rm -rf postgres
fi
```

2022-08-03 13:25 UTC, prashantkhoje commented on p/pgx/pgx_ubi_8.5.sh
> +fi
```suggestion
if [ -d "/usr/local/pgsql/data2" ] ; then
    rm -rf /usr/local/pgsql/data2
fi
```

2022-08-03 13:25 UTC, prashantkhoje commented on p/pgx/pgx_ubi_8.5.sh
> +fi
```suggestion
# Check if package exists
if [ -d "$PACKAGE_NAME" ] ; then
    rm -rf $PACKAGE_NAME
    echo "$PACKAGE_NAME  | $PACKAGE_VERSION | $OS_NAME | GitHub | Removed existing package if any"
fi

if ! git clone $PACKAGE_URL $PACKAGE_NAME; then
    echo "------------------$PACKAGE_NAME:clone_fails---------------------------------------"
    echo "$PACKAGE_URL $PACKAGE_NAME"
    echo "$PACKAGE_NAME  |  $PACKAGE_URL |  $PACKAGE_VERSION | $OS_NAME | GitHub | Fail |  Clone_Fails"
    exit 0
fi
```

2022-08-03 13:25 UTC, prashantkhoje commented on p/pgx/pgx_ubi_8.5.sh
> +fi
```suggestion
cd /home/tester/$PACKAGE_NAME
git checkout $PACKAGE_VERSION

if ! (go build); then
    echo "------------------$PACKAGE_NAME:build failed---------------------"
    echo "$PACKAGE_VERSION $PACKAGE_NAME"
    echo "$PACKAGE_NAME  | $PACKAGE_VERSION | $OS_NAME | GitHub | Fail |  build_Fails"
    exit 1
fi
```

2022-08-03 13:25 UTC, prashantkhoje commented on p/pgx/pgx_ubi_8.5.sh
> +fi
```suggestion
if ! PGX_TEST_DATABASE="host=127.0.0.1 port=5434 database=pgx_test user=pgx_pw password=secret sslmode=disable" go test -v ./...; then
    echo "------------------$PACKAGE_NAME:install_success_but_test_fails---------------------"
    echo "$PACKAGE_URL $PACKAGE_NAME" > /home/tester/output/test_fails
    echo "$PACKAGE_NAME  |  $PACKAGE_URL | $PACKAGE_VERSION | $OS_NAME | GitHub | Fail |  Install_success_but_test_Fails" > /home/tester/output/version_tracker
    exit 1
else
    echo "------------------$PACKAGE_NAME:install_&_test_both_success-------------------------"
    echo "$PACKAGE_VERSION $PACKAGE_NAME" > /home/tester/output/test_success
    echo "$PACKAGE_NAME  |  $PACKAGE_VERSION | $PACKAGE_VERSION | $OS_NAME | GitHub  | Pass |  Both_Install_and_Test_Success" > /home/tester/output/version_tracker
    exit 0
fi
```

2022-08-03 13:26 UTC, prashantkhoje commented on p/pgx/pgx_ubi_8.5.sh
> +#!/bin/bash -e
```suggestion
#!/bin/bash -ex
```

2022-08-04 09:58 UTC, prashantkhoje commented
This PR can be merged

2022-08-08 03:46 UTC, merged