Adding buildscript for package drupal_libraries
ppc64le/build-scripts pull request #2298
Opened 2022-07-01 12:02 UTC by vathsalashetty25

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2022-07-07 11:06 UTC, prashantkhoje commented on d/drupal_libraries/drupal_libraries_ubi_8.5.sh
> +fi
```suggestion
if [ -d "$CORE_PACKAGE_NAME" ] ; then
    rm -rf $CORE_PACKAGE_NAME
    echo "$CORE_PACKAGE_NAME  | $PACKAGE_VERSION | $OS_NAME | GitHub | Removed existing package"
fi
if ! git clone $CORE_PACKAGE_URL $CORE_PACKAGE_NAME; then
    echo "------------------$PACKAGE_NAME:clone_fails---------------------------------------"
    echo "$CORE_PACKAGE_URL $CORE_PACKAGE_NAME"
    echo "$CORE_PACKAGE_NAME  |  $CORE_PACKAGE_URL |  $PACKAGE_VERSION | $OS_NAME | GitHub | Fail |  Clone_Fails"
    exit 1
fi
```

2022-07-07 11:08 UTC, prashantkhoje commented on d/drupal_libraries/drupal_libraries_ubi_8.5.sh
> +fi
```suggestion
if ! composer install --no-interaction; then
    echo "------------------$PACKAGE_NAME:install_fails-------------------------------------"
    echo "$PACKAGE_URL $PACKAGE_NAME"
    echo "$PACKAGE_NAME  |  $PACKAGE_URL | $PACKAGE_VERSION | $OS_NAME | GitHub | Fail |  Install_Fails"
    exit 1
fi

composer require --dev phpunit/phpunit --with-all-dependencies ^7 --no-interaction

cd modules/
# Check if package exists
if [ -d "$PACKAGE_NAME" ] ; then
    rm -rf $PACKAGE_NAME
    echo "$PACKAGE_NAME  | $PACKAGE_VERSION | $OS_NAME | GitHub | Removed existing package"
fi
if ! git clone $PACKAGE_URL $PACKAGE_NAME; then
    echo "------------------$PACKAGE_NAME:clone_fails---------------------------------------"
    echo "$PACKAGE_URL $PACKAGE_NAME"
    echo "$PACKAGE_NAME  |  $PACKAGE_URL |  $PACKAGE_VERSION | $OS_NAME | GitHub | Fail |  Clone_Fails"
    exit 1
fi
```

2022-07-07 11:10 UTC, prashantkhoje commented on d/drupal_libraries/drupal_libraries_ubi_8.5.sh
> +# Please follow README file for more information to run Functional and kernel test cases.
```suggestion
if ! ../vendor/phpunit/phpunit/phpunit ../modules/libraries/tests/src/Unit; then
    echo "------------------$PACKAGE_NAME:install_success_but_test_fails---------------------"
    echo "$PACKAGE_URL $PACKAGE_NAME"
    echo "$PACKAGE_NAME  |  $PACKAGE_URL | $PACKAGE_VERSION | $OS_NAME | GitHub | Fail |  Install_success_but_test_Fails"
    exit 1
else
    echo "------------------$PACKAGE_NAME:install_&_test_both_success-------------------------"
    echo "$PACKAGE_URL $PACKAGE_NAME"
    echo "$PACKAGE_NAME  |  $PACKAGE_URL | $PACKAGE_VERSION | $OS_NAME | GitHub  | Pass |  Both_Install_and_Test_Success"
    exit 0
fi

# Package drupal-libraries has 3 types of tests - Unit/Functional/Kernel. Unit tests don't need drupal framework and DB etc. So they can be executed by given script.
# Please follow README file for more information to run functional and kernel test cases.
```

2022-07-11 10:13 UTC, prashantkhoje commented
Looks good to be merged.

2022-07-14 06:32 UTC, prashantkhoje requested changes

2022-07-14 06:32 UTC, prashantkhoje commented on d/drupal_libraries/README.md
> +
```suggestion
    To run test cases in drupal module, we need drupal core package and drupal complete framework which includes a database, apache server and core package itself.
    There are 3 type of tests in drupal unit, functional, integration. For unit tests, we don't need drupal full framework like database.
    Unit tests don't use database.
```

2022-07-14 06:32 UTC, prashantkhoje commented on d/drupal_libraries/README.md
> +
```suggestion
Copy following files into the VM that is needed to run docker file successfully.
```

2022-07-14 06:32 UTC, prashantkhoje commented on d/drupal_libraries/README.md
> +
```suggestion
Rename following 2 files:-
    # cp Dockerfile.drupal.ubi Dockerfile
    # cp automate_drupal.sh.txt automate_drupal.sh
    # chmod +x automate_drupal.sh
```

2022-07-14 06:32 UTC, prashantkhoje commented on d/drupal_libraries/README.md
> +
```suggestion
Now create an image from dockerfile (Dockerfile.drupal.ubi i.e Dockerfile)
     # docker build -t drupal_image .
     # docker images
```

2022-07-14 06:32 UTC, prashantkhoje commented on d/drupal_libraries/README.md
> +    #cd /opt/app-root/src/drupal/modules
```suggestion
Then run a container using that image.
    # docker run -it -d drupal_image /bin/bash
    # docker ps
    # docker exec -it a025d0a771a8 /bin/bash

Live drupal webserver will be available at http://<ip>:8081

After that we need to run below command inside the container. Run it in single command. Step 1 will take some time to exec.

Step 1:-
    su - postgres -c 'if [[ $(psql -l | grep dru2_pg) ]]; then     echo "Database already configured..."; else    /usr/pgsql-13/bin/pg_ctl -D /var/lib/pgsql/13/data/ start;     /usr/pgsql-13/bin/createdb -T template0 dru2_pg;     psql dru2_pg < /opt/app-root/src/drupal_schema.sql; fi'

Step 2:-
    /usr/sbin/httpd -k start;

step 3 Go to :-
    # cd /opt/app-root/src/drupal/modules
```

2022-07-14 06:32 UTC, prashantkhoje commented on d/drupal_libraries/README.md
> +bash-4.4# ../vendor/phpunit/phpunit/phpunit ../modules/$PACKAGE_NAME/tests
```suggestion
# ../vendor/phpunit/phpunit/phpunit ../modules/$PACKAGE_NAME/tests
```

2022-07-14 06:32 UTC, prashantkhoje commented on d/drupal_libraries/README.md
> +bash-4.4# ../vendor/phpunit/phpunit/phpunit ../modules/$PACKAGE_NAME/tests/src/Unit
```suggestion
# ../vendor/phpunit/phpunit/phpunit ../modules/$PACKAGE_NAME/tests/src/Unit
```

2022-07-14 06:32 UTC, prashantkhoje commented on d/drupal_libraries/README.md
> +bash-4.4# ../vendor/phpunit/phpunit/phpunit ../modules/$PACKAGE_NAME/tests/src/Functional
```suggestion
# ../vendor/phpunit/phpunit/phpunit ../modules/$PACKAGE_NAME/tests/src/Functional
```

2022-07-14 06:32 UTC, prashantkhoje commented on d/drupal_libraries/README.md
> +bash-4.4# ../vendor/phpunit/phpunit/phpunit ../modules/$PACKAGE_NAME/tests/src/Kernel
```suggestion
# ../vendor/phpunit/phpunit/phpunit ../modules/$PACKAGE_NAME/tests/src/Kernel
```

2022-07-26 10:11 UTC, kandarpamalipeddi approved these changes

2022-07-26 10:12 UTC, merged