Added build script for drupal/terms_of_use
ppc64le/build-scripts pull request #2321
Opened 2022-07-05 11:20 UTC by Sunidhi-Gaonkar1

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2022-07-07 03:54 UTC, seth-priya commented
@prashantkhoje please review

2022-07-07 10:15 UTC, prashantkhoje requested changes

2022-07-07 10:15 UTC, prashantkhoje commented on d/drupal-terms_of_use/drupal-terms_of_use_ubi_8.5.sh
> +fi
```suggestion
# Check if package exists
if [ -d "$CORE_PACKAGE_NAME" ] ; then
	rm -rf $CORE_PACKAGE_NAME
	echo "$CORE_PACKAGE_NAME  | $PACKAGE_VERSION | $OS_NAME | GitHub | Removed existing package"
fi

if ! git clone $CORE_PACKAGE_URL $CORE_PACKAGE_NAME; then
	echo "------------------$PACKAGE_NAME:clone_fails---------------------------------------"
	echo "$CORE_PACKAGE_URL $CORE_PACKAGE_NAME"
	echo "$CORE_PACKAGE_NAME  |  $CORE_PACKAGE_URL |  $PACKAGE_VERSION | $OS_NAME | GitHub | Fail |  Clone_Fails"
	exit 1
fi
```

2022-07-07 10:15 UTC, prashantkhoje commented on d/drupal-terms_of_use/drupal-terms_of_use_ubi_8.5.sh
> +fi
```suggestion
if ! composer install --no-interaction; then
	echo "------------------$PACKAGE_NAME:install_fails-------------------------------------"
	echo "$PACKAGE_URL $PACKAGE_NAME"
	echo "$PACKAGE_NAME  |  $PACKAGE_URL | $PACKAGE_VERSION | $OS_NAME | GitHub | Fail |  Install_Fails"
	exit 1
fi
```

2022-07-07 10:15 UTC, prashantkhoje commented on d/drupal-terms_of_use/drupal-terms_of_use_ubi_8.5.sh
> +fi
```suggestion
# Check if package exists
if [ -d "$PACKAGE_NAME" ] ; then
	rm -rf $PACKAGE_NAME
	echo "$PACKAGE_NAME  | $PACKAGE_VERSION | $OS_NAME | GitHub | Removed existing package"
fi

if ! git clone $PACKAGE_URL $PACKAGE_NAME; then
	echo "------------------$PACKAGE_NAME:clone_fails---------------------------------------"
	echo "$PACKAGE_URL $PACKAGE_NAME"
	echo "$PACKAGE_NAME  |  $PACKAGE_URL |  $PACKAGE_VERSION | $OS_NAME | GitHub | Fail |  Clone_Fails"
	exit 1
fi
```

2022-07-07 10:15 UTC, prashantkhoje commented on d/drupal-terms_of_use/drupal-terms_of_use_ubi_8.5.sh
> +#No test cases available.
```suggestion
echo "The test cases are not available."
```

2022-07-08 07:24 UTC, Sunidhi-Gaonkar1 commented
@prashantkhoje Please review.

2022-07-11 10:17 UTC, prashantkhoje commented
LGTM

2022-07-11 10:36 UTC, merged