added build script for yaeti
ppc64le/build-scripts pull request #2380
Opened 2022-07-14 11:34 UTC by saraswati-patra

added build script for yaeti

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [x] Did you have **Legal approvals** for patch files ?

2022-07-21 06:30 UTC, kumarvikas2020 requested changes

2022-07-21 06:30 UTC, kumarvikas2020 commented on y/yaeti/yaeti_ubi_8.5.sh
> +#https://jazz06.rchland.ibm.com:12443/jazz/web/projects/Power%20Ecosystem#action=com.ibm.team.workitem.viewWorkItem&id=149836
@saraswati-patra Please remove non-public link from the script.

2022-07-21 06:32 UTC, kumarvikas2020 requested changes

2022-07-21 06:32 UTC, kumarvikas2020 commented on y/yaeti/yaeti_ubi_8.5.sh
> +#https://jazz06.rchland.ibm.com:12443/jazz/web/projects/Power%20Ecosystem#action=com.ibm.team.workitem.viewWorkItem&id=149836
@saraswati-patra Please remove the non-public link from the script.

2022-07-27 04:30 UTC, seth-priya commented
@kumarvikas2020 please review

2022-08-22 08:28 UTC, seth-priya commented
@saraswati-patra @kumarvikas2020 any update on this one?

2022-08-23 11:21 UTC, kumarvikas2020 commented
@seth-priya LGTM

2022-08-23 11:22 UTC, kumarvikas2020 approved these changes

2022-08-23 11:22 UTC, kumarvikas2020 approved these changes

2022-08-23 11:23 UTC, merged