Added build script for xtgo_uuid package built on UBI:8.5
ppc64le/build-scripts pull request #2533
Opened 2022-08-03 11:30 UTC by Balavva-Mirji

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2022-08-03 12:47 UTC, afsanjar commented on x/xtgo__uuid/xtgo_uuid_ubi_8.5.sh
> +go test -v ./...
There is no check for errors and failures in the script.

2022-08-04 05:15 UTC, seth-priya requested changes

2022-08-04 05:15 UTC, seth-priya commented on x/xtgo__uuid/xtgo_uuid_ubi_8.5.sh
> +# Package	     : github.com/xtgo/uuid
@Balavva-Mirji please check the indentation for this full section

2022-08-08 03:54 UTC, seth-priya approved these changes

2023-01-30 11:33 UTC, merged