Added  requested version for csstype
ppc64le/build-scripts pull request #2642
Opened 2022-08-22 09:10 UTC by saraswati-patra

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2022-08-23 05:27 UTC, seth-priya commented
@saraswati-patra  is the inclusion of the "csstype_RHEL7.6.sh.bak" file in this commit intentional?

2022-08-23 06:36 UTC, saraswati-patra commented
> @saraswati-patra is the inclusion of the "csstype_RHEL7.6.sh.bak" file in this commit intentional?

Added .bak file wrongly,Deleted and commit.thanks

2022-09-05 05:41 UTC, seth-priya requested changes

2022-09-05 05:41 UTC, seth-priya commented on c/csstype/csstype_RHEL7.6.sh
> +# Tested on     : RHEL 7.6,8.5
this should be RHEL 7.6, RHEL 8.5 for consistency

2022-09-05 05:42 UTC, seth-priya commented
@vathsalashetty25 @kumarvikas2020 if @saraswati-patra  can't , can one of you handle this?

2023-01-31 04:20 UTC, seth-priya approved these changes

2023-01-31 04:20 UTC, merged