esapi-java-legacy:scriptadded
ppc64le/build-scripts pull request #2751
Opened 2022-09-13 12:26 UTC by ankitpar

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2022-09-13 12:30 UTC, ankitpar commented
Build Script on travis might fail as gpg needed userinput Genkey if not already installed.

2022-09-21 10:45 UTC, seth-priya requested changes

2022-09-21 10:45 UTC, seth-priya commented on e/esapi_java_legacy/esapijavalegacy.sh
> +# Maintainer    : BulkPackageSearch Automation {maintainer}
Please mention your name, email here

2022-09-21 10:45 UTC, seth-priya commented on e/esapi_java_legacy/esapijavalegacy.sh
> +yum -y update --allowerasing --skip-broken --nobest
why do we need this?

2022-09-26 05:10 UTC, ankitpar commented on e/esapi_java_legacy/esapijavalegacy.sh
> +# Maintainer    : BulkPackageSearch Automation {maintainer}
Fixed

2022-09-26 05:10 UTC, ankitpar commented on e/esapi_java_legacy/esapijavalegacy.sh
> +yum -y update --allowerasing --skip-broken --nobest
Fixed

2023-01-31 05:03 UTC, seth-priya commented
Made changes to remove mvn test as mvn install anyway runs the tests and also address previous review comments, travis check in progress

2023-01-31 06:50 UTC, seth-priya commented
The failure condition was returning an exit 0 , hence the build failure is not caught on travis, this needs to be fixed

2026-01-02 09:32 UTC, seth-priya commented
https://github.com/ppc64le/build-scripts/blob/master/e/esapi-java-legacy/esapi-java-legacy_ubi_8.5.sh newer version of the script

2026-01-02 09:32 UTC, closed without merging