added netty package to currency automation
ppc64le/build-scripts pull request #2839
Opened 2022-10-18 09:31 UTC by mohitp333

## Checklist

- [ ] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [ ] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2023-01-03 11:10 UTC, seth-priya commented
@mohitp333 please check the travis build failure

2023-02-08 11:20 UTC, seth-priya commented
@nikhil-kalbande

2023-02-10 11:05 UTC, nikhil-kalbande requested changes

2023-02-10 11:05 UTC, nikhil-kalbande commented on n/netty/netty-4.1.84.Final_ubi_8.5.sh
> +    exit 2
@mohitp333  please make this exit 1

2023-02-10 11:05 UTC, nikhil-kalbande commented on n/netty/netty-4.1.84.Final_ubi_8.5.sh
> +# Version       : netty-4.1.79.Final
@mohitp333 correct this version to version you tested/added script

2023-02-10 12:58 UTC, nikhil-kalbande approved these changes

2023-02-10 12:59 UTC, merged