Added build script for metricbeat
ppc64le/build-scripts pull request #2892
Opened 2022-12-09 12:18 UTC by Sunidhi-Gaonkar1

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2022-12-22 07:58 UTC, seth-priya requested changes

2022-12-22 07:58 UTC, seth-priya commented on m/metricbeat/metricbeat.diff
> ++    image: ibmcom/elasticsearch-ppc64le:8.3.3
it's better to reference the icr.io images here

2022-12-22 07:58 UTC, seth-priya commented on m/metricbeat/metricbeat.diff
> ++    image: ibmcom/kibana-ppc64le:8.1.0
better to reference the icr.io images

2022-12-22 08:04 UTC, Sunidhi-Gaonkar1 commented on m/metricbeat/metricbeat.diff
> ++    image: ibmcom/kibana-ppc64le:8.1.0
Sure, I will make the changes.

2023-01-06 11:29 UTC, seth-priya approved these changes

2023-01-06 11:29 UTC, merged