Added build script fot jupyter-base-notebook
ppc64le/build-scripts pull request #2919
Opened 2022-12-28 04:31 UTC by muskaan2199

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2023-01-03 11:09 UTC, seth-priya commented
@muskaan2199 please check the travis build failure

2023-01-10 06:56 UTC, nikhil-kalbande requested changes

2023-01-10 06:56 UTC, nikhil-kalbande commented on j/jupyter-base-notebook/jupyter-base-notebook_ubi_8.5.sh
> +jlpm build
@muskaan2199 - Can we handle failures for build and test separately with exit codes 1 and 2. Please do that

2023-01-10 06:59 UTC, nikhil-kalbande commented
@muskaan2199 - 
1. I dont see build_info file in PR. 
2. Also have you validated dockerfile for latest version of jupyter-base-notebook. Do we need changes there?

2023-01-12 04:24 UTC, muskaan2199 commented
> @muskaan2199 -
> 
> 1. I dont see build_info file in PR.
> 2. Also have you validated dockerfile for latest version of jupyter-base-notebook. Do we need changes there?

@nikhil-kalbande 
I'm waiting for the Dockerfile to be added to build script repository. After that I will add those.
Made changes and added exit conditions.

2023-02-12 16:02 UTC, closed without merging