Added build script, build info and dockerfile for antlr4
ppc64le/build-scripts pull request #2952
Opened 2023-01-18 13:27 UTC by muskaan2199

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2023-01-20 01:48 UTC, kandarpamalipeddi requested changes

2023-01-20 01:48 UTC, kandarpamalipeddi commented on a/antlr4/Dockerfiles/ubi-8.5/Dockerfile
> +ARG ANTLR_VERSION="4.11.1"
By defualt we send the `$PACKAGE_VERSION` argument to our build script and Docker file.
So in this case, we never send ANTLR_VERSION, hence it always build 4.11.1 version.

To fix this, either assign ANTLR_VERSION with `$PACKAGE_VERSION` in `build_info.json` file in `args` section or rename ANTLR_VERSION arg to PACKAGE_VERSION.

2023-01-20 01:48 UTC, kandarpamalipeddi commented on a/antlr4/Dockerfiles/ubi-8.5/Dockerfile
> +RUN adduser \
We are creating a user but not using/setting it.
Can you please check it once?

2023-01-20 01:48 UTC, kandarpamalipeddi commented on a/antlr4/antlr4_v4.11.1_ubi_8.5.sh
> +		exit 2
If Build fails, `return 1`/`exit 1`.

2023-01-31 04:05 UTC, muskaan2199 commented
@kandarpamalipeddi @nikhil-kalbande made the required changes. Please review. Regarding the user part it's the same in the existing dockerfile hence have done the same made the remaining changes

2023-01-31 09:40 UTC, nikhil-kalbande commented on a/antlr4/antlr4_v4.11.1_ubi_8.5.sh
> +PACKAGE_VERSION=v4.11.1
@muskaan2199  - can you please make change to accept PACKAGE_VERSION as param.
like PACKAGE_VERSION=${1:-v4.11.1}

2023-01-31 10:26 UTC, merged