Currency:Added build-script,build_info and Dockerfile for tinkerpop
ppc64le/build-scripts pull request #2986
Opened 2023-02-09 11:41 UTC by vinodk99

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2023-02-14 11:39 UTC, vinodk99 commented
@nikhil-kalbande ,Can you please review this PR.

2023-02-14 12:01 UTC, nikhil-kalbande requested changes

2023-02-14 12:01 UTC, nikhil-kalbande commented on t/tinkerpop/tinkerpop_ubi_8.5.sh
> +if ! mvn clean install -pl -:gremlin-javascript,-:gremlin-server ; then
@vinodk99 Lets separate out build and test step if possible

2023-02-22 09:47 UTC, vinodk99 commented
Travis check is failing due to job exceeding long length,so attaching logs for reference.
[tinkerpop_logs.txt](https://github.com/ppc64le/build-scripts/files/10802190/tinkerpop_logs.txt)

2023-03-06 07:46 UTC, nikhil-kalbande approved these changes

2023-03-06 07:46 UTC, merged