Currency:Add build script for configbump: v0.1.5
ppc64le/build-scripts pull request #3048
Opened 2023-03-07 08:19 UTC by shreyakajbaje

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2023-03-09 13:48 UTC, shreyakajbaje commented
attaching logs for reference - [configbumpBuildTestsLogs.txt](https://github.com/ppc64le/build-scripts/files/10932195/configbumpBuildTestsLogs.txt)

2023-03-09 13:56 UTC, shreyakajbaje commented
Additional Details - 

Machine: Power Linux 03af3a271a93 3.10.0-1160.6.1.el7.ppc64le
OS NAME="Red Hat Enterprise Linux"
OS VERSION="8.7 (Ootpa)"
GO VERSION: 1.13

2023-03-10 03:49 UTC, nikhil-kalbande requested changes

2023-03-10 03:49 UTC, nikhil-kalbande commented on c/Configbump/build-info.json
> +    "package_dir": "c/Configbump",
@shreyakajbaje we expect the package folder will all small case, so please update directory name. `c/configbump`

2023-03-10 03:49 UTC, nikhil-kalbande commented on c/Configbump/configbump_ubi_8.5.sh
> +export GOPATH=/home/go
@shreyakajbaje This doesn't look correct and may break in different environment.
Refer - https://github.com/ppc64le/build-scripts/blob/master/o/opentelemetry-go-contrib/opentelemetry-go-contrib_ubi_8.5.sh#L26-L29

2023-03-22 10:17 UTC, nikhil-kalbande approved these changes

2023-03-22 10:17 UTC, merged