Currency:Added build-script and build_info.json for htslib
ppc64le/build-scripts pull request #3066
Opened 2023-03-16 10:16 UTC by vinodk99

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2023-03-27 05:09 UTC, vinodk99 commented
@nikhil-kalbande  ,Can you review this PR.

2023-03-28 05:57 UTC, nikhil-kalbande requested changes

2023-03-28 05:57 UTC, nikhil-kalbande commented on h/htslib/htslib_ubi_8.5.sh
> +yum update -y
@vinodk99 We need to avoid yum update. Can you please install only required tools or packages and check this

2023-03-28 05:57 UTC, nikhil-kalbande commented on h/htslib/htslib_ubi_8.5.sh
> +      echo "$PACKAGE_NAME  |  $PACKAGE_URL | $PACKAGE_VERSION | $OS_NAME | GitHub  | Fail | Install_fails"
For install failures also we can return 1 with exit 1

2023-03-28 05:57 UTC, nikhil-kalbande commented on h/htslib/build_info.json
> +}
Please see if we can continue to support old script for old version by adding regex in build_info.json

2023-03-29 04:20 UTC, vinodk99 commented
@nikhil-kalbande ,Can you review this PR.

2023-04-04 13:54 UTC, nikhil-kalbande approved these changes

2023-04-04 13:54 UTC, merged