Create rear.travis.yml
ppc64le/build-scripts pull request #321
Opened 2020-12-28 11:11 UTC by gururajrkatti

Original .travis.yml was giving parse error. Corrected it. Also added "make install" based on the build script.

2020-12-28 11:20 UTC, seth-priya commented
@gururajrkatti do we need this, I see the upstream repo at https://github.com/rear/rear/blob/master/.travis.yml already has ppc64le support?

2020-12-28 11:35 UTC, gururajrkatti commented
Hi @seth-priya, thanks for the response and feedback. When I checked the repos, I could not see any travis build running, I tried to trigger it myself, I was seeing parse error. Hence modified it a bit. Also, based on the dockerfile in build script, I added one more step to the travis job.

2020-12-28 13:06 UTC, seth-priya commented
Ok, that seems interesting - although I have no particular issues in merging this PR, in this case, I would actually recommend that you go back to the community and *fix* their job, especially if the issue is seen on Intel as well? The install step maybe unnecessary in travis.yml , but again no harm in having it in either

2020-12-29 06:36 UTC, seth-priya requested changes

2020-12-29 06:36 UTC, seth-priya commented on travis-ymls/rear.travis.yml
> +# Source Repo         : https://github.com/gururajrkatti/rear
Please mention the link to the original repo. instead of the forked one.

2020-12-30 03:48 UTC, gururajrkatti commented
@seth-priya, community has accepted this change

2020-12-30 04:00 UTC, seth-priya commented
Thanks @gururajrkatti for the update and for following through on this! In that case I don't think we need  it here

2020-12-30 04:00 UTC, closed without merging