Currency:Updated build_script and build_info for apache_arrow
ppc64le/build-scripts pull request #3255
Opened 2023-06-28 11:54 UTC by vinodk99

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2023-06-30 05:08 UTC, nikhil-kalbande approved these changes

2023-06-30 05:47 UTC, vinodk99 commented
Travis check is failing due to job exceeding maximum length,Attaching logs for reference.
[Arrow_Build&Test_logs.txt](https://github.com/ppc64le/build-scripts/files/11913263/Arrow_Build.Test_logs.txt)

2023-07-06 06:54 UTC, nikhil-kalbande requested changes

2023-07-06 06:54 UTC, nikhil-kalbande commented on a/apache-arrow/build_info.json
> +    "go/v12.0.*" : {
Here we dont want to remove support for old version. SO better to keep old entry along with new version

2023-07-06 06:54 UTC, nikhil-kalbande commented on a/apache-arrow/arrow_ubi_8.7.sh
> +GO_VERSION=${GO_VERSION:-1.20.3}
Updating go version every time is creating maintenance headache. So @vinodk99  please see if we can make this dynamic or any additional step to be added so we wont need to update build script for go version only. I'm ok for this PR but just question to address .

2023-07-19 12:18 UTC, merged