Fluent bit v2.1.10 Script and Dockerfile with currency
ppc64le/build-scripts pull request #3357
Opened 2023-10-04 08:21 UTC by sumitd2

## Checklist

- [X] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [X] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [X] Did you have **Legal approvals** for patch files ?

2023-10-09 11:19 UTC, seth-priya approved these changes

2023-10-09 11:19 UTC, seth-priya commented
LGTM , @nikhil-kalbande please check once from currency side

2023-10-10 08:51 UTC, nikhil-kalbande requested changes

2023-10-10 08:51 UTC, nikhil-kalbande commented on f/fluent-bit/fluent-bit_v2.1.10_ubi_8.7.sh
> +PKG_NAME=fluent-bit
@sumitd2 Please change variable names in format like PACKAGE_NAME... use PACKAGE in place of PKG. Otherwise I am good with PR for merge

2023-10-10 13:19 UTC, nikhil-kalbande approved these changes

2023-10-10 13:20 UTC, merged