rules_rust 0.28.0 Script
ppc64le/build-scripts pull request #3368
Opened 2023-10-12 10:41 UTC by sumitd2

## Checklist

- [X] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [X] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [X] Did you have **Legal approvals** for patch files ?

2023-10-27 09:57 UTC, seth-priya commented
@nikhil-kalbande please check the build-info changes once

2023-10-30 05:54 UTC, nikhil-kalbande requested changes

2023-10-30 05:54 UTC, nikhil-kalbande commented on r/rules_rust/build_info.json
> +    "0.28.0" : {
@sumitd2 Let's use `0.28.*` so for any future minor release version currency build can use this new script.
Also please update version (row5) and build_script (row8), so any future version can by default will try running with new script you are adding if not matching pattern found.

2023-11-24 07:47 UTC, sumitd2 commented
@nikhil-kalbande Done, hope I ve got it right

2023-11-24 08:52 UTC, nikhil-kalbande approved these changes

2023-11-24 08:53 UTC, merged