Generalizing Automation Code
ppc64le/build-scripts pull request #3404
Opened 2023-11-02 14:15 UTC by shubham-garud

## Checklist

- [ ] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [ ] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2023-11-02 15:05 UTC, atharv-phadnis requested changes

2023-11-02 15:05 UTC, atharv-phadnis commented on script/node_bs.py
> +    with open (f"{current_directory}/templates/{script_language}",'w') as newfile:
Can we simply use the destination path use in this script later (L192) here itself `f"{dir_name}/{package_name}_ubi_8.7.sh"`? It'll save the extra steps below. Only the command `new_cmd=f"python3 script/trigger_container.py -f templates/{script_language}"` (L193) we also need to be modified to use this path instead

2023-11-03 07:23 UTC, atharv-phadnis approved these changes

2023-11-03 09:55 UTC, atharv-phadnis approved these changes

2023-11-16 12:26 UTC, atharv-phadnis approved these changes

2023-12-12 09:37 UTC, atharv-phadnis approved these changes

2023-12-12 09:50 UTC, nikhil-kalbande approved these changes

2023-12-12 09:50 UTC, merged