Build script for Logstash v8.11.3
ppc64le/build-scripts pull request #3472
Opened 2023-12-21 04:44 UTC by Sapana-Khemkar

## Checklist

- [ ] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [ ] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2024-01-10 13:56 UTC, nikhil-kalbande requested changes

2024-01-11 11:44 UTC, Sapana-Khemkar commented on l/logstash/logstash_8.11.3_ubi_8.9.sh
> +# Tested on	: UBI_8.9
No this is not required. I used ubi latest version. Scripts works on both UBI8.7 and UBI8.9. I will update it accordingly

2024-01-11 13:15 UTC, Sapana-Khemkar commented on l/logstash/build_info.json
> +}
@nikhil-kalbande  Updated build_info.json to use with currency. Please check once

2024-02-14 12:05 UTC, nikhil-kalbande approved these changes

2024-02-14 12:49 UTC, merged