Add build script for Keycloak
ppc64le/build-scripts pull request #3498
Opened 2023-12-28 11:54 UTC by Chandranana

## Checklist

- [X] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [X] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2023-12-28 13:59 UTC, nikhil-kalbande requested changes

2023-12-28 13:59 UTC, nikhil-kalbande commented on k/keycloak/keycloak_ubi_8.7.sh
> +# Version	: v22.0.4
this should be without v?

2023-12-28 13:59 UTC, nikhil-kalbande commented on k/keycloak/keycloak_ubi_8.7.sh
> +	exit 0
should be exit 2 for test failure

2023-12-28 13:59 UTC, nikhil-kalbande commented on k/keycloak/build_info.json
> +    "package_name" : "keyclaok",
correct typo here

2023-12-29 07:51 UTC, Chandranana commented on k/keycloak/keycloak_ubi_8.7.sh
> +# Version	: v22.0.4
Done

2024-01-04 09:02 UTC, nikhil-kalbande commented on k/keycloak/keycloak_ubi_8.7.sh
> +	exit 0
@Chandranana  This is still not done?

2024-01-04 09:03 UTC, nikhil-kalbande approved these changes

2024-01-04 09:04 UTC, merged