AddingPowerSupport_aaargh
ppc64le/build-scripts pull request #356
Opened 2020-12-31 12:23 UTC by santosh653

creating aaargh.travis.yml with proposed changes.,

2021-01-03 08:09 UTC, seth-priya requested changes

2021-01-03 08:09 UTC, seth-priya commented on travis-ymls/aaargh.travis.yml
> +# Source Repo         : https://github.com/apache/arrow
The commit and the file name suggest that this for package "aargh", but the contents seem to be for "pyaarow", please check and update.

2021-01-04 07:00 UTC, seth-priya commented
@santosh653 please squash the commits

2021-01-04 07:12 UTC, santosh653 commented
@seth-priya can you please check now?

2021-01-07 02:41 UTC, seth-priya commented
@santosh653 I still see 4 commits

2021-01-07 09:23 UTC, santosh653 commented
I am closing this pull request.

2021-01-07 09:23 UTC, closed without merging