Cookies develop
ppc64le/build-scripts pull request #3660
Opened 2024-03-22 13:54 UTC by mohitp333

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2024-04-03 13:31 UTC, nikhil-kalbande approved these changes

2024-04-03 13:31 UTC, nikhil-kalbande commented on c/cookies/build_info.json
> +      "build_script": "cookies_ubi_8.7.sh"
script name should have ubi 9.3 reference.
update same in all places @mohitp333

2024-04-03 13:33 UTC, nikhil-kalbande requested changes

2024-04-03 13:33 UTC, nikhil-kalbande commented on c/cookies/build_info.json
> +      "build_script": "cookies_ubi_8.7.sh"
script name should have ubi 9.3 reference.
update same in all places @mohitp333

2024-04-04 12:40 UTC, mohitp333 commented
Hi, @nikhil-kalbande  please check the required changes.

2024-04-17 05:06 UTC, nikhil-kalbande approved these changes

2024-04-17 05:06 UTC, merged