Currency : Added ubi9.3 script and dockerfile for zipkin
ppc64le/build-scripts pull request #3776
Opened 2024-04-30 09:14 UTC by stutiibm

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Have you validated script on UBI 9 container
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2024-05-23 10:12 UTC, nikhil-kalbande requested changes

2024-05-23 10:12 UTC, nikhil-kalbande commented on z/zipkin/build_info.json
> +    }
keep old version supported details like 
```
"2.24.*": {

    "dir": "2.24.2_ubi_8_7",

    "build_script": "zipkin_ubi_8_7.sh"

  },

  "2.20.0": {

    "build_script": "zipkin_ubi_8.5.sh"

  }

}
````

2024-05-23 11:06 UTC, stutiibm commented on z/zipkin/build_info.json
> +    }
Done required changes

2024-05-28 04:19 UTC, nikhil-kalbande approved these changes

2024-05-28 04:19 UTC, merged