Currency : Added ubi9 script for js-cookie
ppc64le/build-scripts pull request #3866
Opened 2024-05-21 05:20 UTC by stutiibm

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Have you validated script on UBI 9 container
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2024-05-23 10:10 UTC, nikhil-kalbande requested changes

2024-05-23 10:10 UTC, nikhil-kalbande commented on j/js-cookie/build_info.json
> +  "v3.0.5, v3.0.4, v3.0.1, v3.0.0": {
lets make it v*.*.*

2024-05-23 11:09 UTC, stutiibm commented on j/js-cookie/build_info.json
> +  "v3.0.5, v3.0.4, v3.0.1, v3.0.0": {
Done required changes

2024-05-28 04:19 UTC, nikhil-kalbande approved these changes

2024-05-28 04:19 UTC, merged