Currency:Updated build-script,build_info.json for odoo
ppc64le/build-scripts pull request #3940
Opened 2024-06-11 09:10 UTC by vinodk99

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Have you validated script on UBI 9 container
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2024-06-11 11:56 UTC, nikhil-kalbande approved these changes

2024-06-11 11:57 UTC, nikhil-kalbande requested changes

2024-06-12 05:39 UTC, vinodk99 commented on o/odoo/build_info.json
>    }
@nikhil-kalbande to build dockerfile for ubi9 it requires postgresql client which is not supported for rhel9.

2024-06-13 08:59 UTC, nikhil-kalbande approved these changes

2024-06-13 08:59 UTC, merged