Added power support for the travis.yml file with ppc64le
ppc64le/build-scripts pull request #398
Opened 2021-01-06 07:29 UTC by sreekanth370

Added power support for the travis.yml file with ppc64le. This is part of the Ubuntu distribution for ppc64le. 
This helps us simplify testing later when distributions are re-building and re-releasing

2021-01-07 02:51 UTC, seth-priya requested changes
@sreekanth370 is this file correct? I don't see any matrix similar to what we have here https://github.com/pyparsing/pyparsing/blob/master/.travis.yml and am not sur how its working, am I missing something??

2021-01-07 04:46 UTC, sreekanth370 commented
Hi priya , 
 updated correctly , kindly check it .

here is the right file which i have  Add ppc64le arch to travis.yml
https://github.com/sreekanth370/pyparsing/blob/master/.travis.yml

2021-01-11 14:05 UTC, sreekanth370 commented
i have done the squash commits , kindly check it ..

2021-02-11 06:37 UTC, sreekanth370 commented
any update on these PR ? still it open let me know if you require more info

2021-02-11 06:41 UTC, sreekanth370 commented
tag @gururajrkatti

2021-02-15 06:13 UTC, merged