Created Script for jackson-core v2.17.0 and Updated build_info.json
ppc64le/build-scripts pull request #3991
Opened 2024-06-21 09:44 UTC by pratibh-ibm

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Have you validated script on UBI 9 container
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2024-06-21 10:13 UTC, prachikurade1 approved these changes
Approved

2024-06-21 11:16 UTC, prachikurade1 requested changes

2024-06-21 11:16 UTC, prachikurade1 commented on j/jackson-core/jackson-core_ubi_9.3.sh
> +PACKAGE_VERSION=jackson-core-2.17.0
As suggested by @nikhil-kalbande on your other PR, please update the package version here as well.
PACKAGE_VERSION=${1:-jackson-core-2.17.0}.

2024-06-24 10:21 UTC, nikhil-kalbande approved these changes

2024-06-24 10:21 UTC, merged