Created Script for jackson-modules-java8-datatypes and added buid_info.json and License.
ppc64le/build-scripts pull request #3994
Opened 2024-06-24 06:28 UTC by santhoshkotla2929

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Have you validated script on UBI 9 container
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2024-06-24 11:15 UTC, nikhil-kalbande requested changes

2024-07-03 13:15 UTC, prachikurade1 requested changes

2024-07-03 13:15 UTC, prachikurade1 commented on j/jackson-modules-java8-datatypes/LICENSE
> + Apache License
Fix indentation.

2024-07-03 13:15 UTC, prachikurade1 commented on j/jackson-modules-java8-datatypes/jackson_modules-java8-datatypes_ubi_9.3.sh
> +# Version       : 2.14.3
Match version as mentioned in build_info.json

2024-07-03 13:15 UTC, prachikurade1 commented on j/jackson-modules-java8-datatypes/jackson_modules-java8-datatypes_ubi_9.3.sh
> +# Package       : com.fasterxml.jackson.datatype:jackson-datatype-jdk8
Package name should match build_info.json

2024-07-04 05:33 UTC, prachikurade1 approved these changes
Approved

2024-07-04 09:30 UTC, prachikurade1 requested changes

2024-07-04 09:30 UTC, prachikurade1 commented on j/jackson-modules-java8-datatypes/build_info.json
> +    "2.*.*": {
This version will be `jackson-modules-java8-2.*.*`

2024-07-04 12:34 UTC, prachikurade1 approved these changes
Approved

2024-07-08 10:42 UTC, nikhil-kalbande approved these changes

2024-07-08 11:28 UTC, merged