Created Script for the classmate v1.5.1 and added build_info.json
ppc64le/build-scripts pull request #3997
Opened 2024-06-24 09:20 UTC by pratibh-ibm

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Have you validated script on UBI 9 container
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2024-07-03 09:12 UTC, prachikurade1 requested changes
Additionally the folder, script names should match package name so it will be j/java-classmate, and java-classmate_ubi_9.3

2024-07-03 09:12 UTC, prachikurade1 commented on c/classmate/classmate_ubi_9.3.sh
> +# Version       : 1.5.1
Update version to match the version in build info.json

2024-07-03 12:28 UTC, pratibh-ibm commented
Previous version for the package were built in this folder, so didn't create new java-classmate folder.

2024-07-04 10:37 UTC, prachikurade1 requested changes

2024-07-04 10:37 UTC, prachikurade1 commented on c/classmate/build_info.json
> +    "1.*.*": {
Need to fix the version regex as discussed.

2024-07-09 10:06 UTC, prachikurade1 approved these changes
Approved

2024-07-09 10:06 UTC, merged