Created Script for guava-guava and added build_info.json and License
ppc64le/build-scripts pull request #4007
Opened 2024-06-25 09:01 UTC by santhoshkotla2929

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Have you validated script on UBI 9 container
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2024-07-04 12:34 UTC, prachikurade1 requested changes

2024-07-04 12:34 UTC, prachikurade1 commented on g/guava-guava/build_info.json
> +    "package_name": "guava-guava",
Can name package as guava. Please update folder, script and any other place applicable.

2024-07-04 12:34 UTC, prachikurade1 commented on g/guava-guava/guava-guava_ubi_9.3.sh
> +REPO_NAME="guava"
Dont need repo name and package name since they have the same value. Can use package name variable only for this case.

2024-07-10 05:10 UTC, santhoshkotla2929 commented
No Longer Required

2024-07-10 05:10 UTC, closed without merging