Currency: Added build-script and build_info.json for governator
ppc64le/build-scripts pull request #4099
Opened 2024-07-09 09:05 UTC by pooja0805

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Have you validated script on UBI 9 container
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2024-07-10 12:47 UTC, nikhil-kalbande requested changes

2024-07-10 12:47 UTC, nikhil-kalbande commented on g/governator/build_info.json
> +    "package_dir": "s/spring-plugin/",
@pooja0805 this is incorrect

2024-07-10 13:06 UTC, pooja0805 commented on g/governator/build_info.json
> +    "package_dir": "s/spring-plugin/",
Updated.

2024-07-15 15:05 UTC, nikhil-kalbande approved these changes

2024-07-15 15:05 UTC, merged