Added power support for the travis.yml file with ppc64le
ppc64le/build-scripts pull request #410
Opened 2021-01-07 09:38 UTC by sreekanth370

Added power support for the travis.yml file with ppc64le. This is part of the Ubuntu distribution for ppc64le. 
This helps us simplify testing later when distributions are re-building and re-releasing.

2021-01-08 10:20 UTC, gururajrkatti requested changes
@sreekanth370 I see that you have added a simple "- echo "SAMPLE TRAVIS JOB"" in the script. Will it not just run the echo statement as part of build ? Pl. check. Also check the indentation. E.g.,language

2021-01-08 11:12 UTC, sreekanth370 commented
updated  travis.yml file ,  kindly check it .

2021-01-11 04:06 UTC, gururajrkatti requested changes
Can you pl. squash the commits

2021-01-11 06:34 UTC, sreekanth370 commented
I have squash the earlier updates . kindly check it .

2021-01-11 08:19 UTC, gururajrkatti approved these changes
LGTM

2021-01-11 09:57 UTC, merged