PR_AddingPowerSupport_fs-extra
ppc64le/build-scripts pull request #416
Opened 2021-01-07 13:11 UTC by santosh653

creating fs-extra.travis.yml with proposed changes.,

2021-01-10 10:17 UTC, santosh653 commented
@gururajrkatti @Siddhesh-Ghadi Can you please review this PR?

2021-01-11 05:32 UTC, gururajrkatti requested changes
Isn't the file name and "Package" in the file be named as "node-fs-extra" as per the repos name ? Isn't the node12 be running with env set as TEST_SUITE=full-ci ?

2021-01-11 08:31 UTC, santosh653 commented
@gururajrkatti The package name in our Tracking/Status sheet stands as **fs_extra** & as per the standard convention we have been following, the Travis file name for a PR to be ideally in the format <your_project_name>.travis.yml and hence even the package name in the Travis file. Please correct me if wrong !!

I have now included node12 while the env set as TEST_SUITE=full-ci.
Thanks !!

2021-01-11 12:02 UTC, gururajrkatti approved these changes

2021-01-11 12:44 UTC, merged