Currency: Added build-script and build_info.json for hibernate-common-annotations
ppc64le/build-scripts pull request #4174
Opened 2024-07-23 09:20 UTC by pooja0805

…s-annotations

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Have you validated script on UBI 9 container
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2024-07-25 10:01 UTC, nikhil-kalbande requested changes

2024-07-25 10:01 UTC, nikhil-kalbande commented on h/hibernate-commons-annotations/hibernate-commons-annotations_ubi_9.3.sh
> +if ! ./gradlew clean build -x test; then
@pooja0805 same comment as other PR 
![Uploading image.png…]()

2024-07-25 10:04 UTC, pooja0805 commented on h/hibernate-commons-annotations/hibernate-commons-annotations_ubi_9.3.sh
> +if ! ./gradlew clean build -x test; then
Sure. I will update accordingly

2024-07-25 10:21 UTC, pooja0805 commented
@nikhil-kalbande Updated the echo commands according to the mentioned format.

2024-07-26 04:30 UTC, nikhil-kalbande approved these changes

2024-07-26 04:30 UTC, merged