PR_AddigPowerSupport_kaniko
ppc64le/build-scripts pull request #421
Opened 2021-01-07 14:09 UTC by santosh653

creating kaniko.travis.yml with proposed changes.

2021-01-08 04:35 UTC, Siddhesh-Ghadi requested changes

2021-01-08 04:35 UTC, Siddhesh-Ghadi commented on travis-ymls/kaniko.travis.yml
> +  - ppc64le
This changes will not create builds properly as build matrix is defined using `jobs`.

2021-01-08 04:35 UTC, Siddhesh-Ghadi commented on travis-ymls/kaniko.travis.yml
> +  include:
Please add ppc64le jobs under this.

2021-02-09 03:03 UTC, gururajrkatti commented
@santosh653 any updates on this ?

2021-02-18 10:44 UTC, gururajrkatti commented
@santosh653 any updates on this ?

2021-02-23 12:46 UTC, gururajrkatti commented
@santosh653 any updates on this

2021-03-01 14:04 UTC, gururajrkatti commented
@santosh653 any updates on this

2021-03-02 04:56 UTC, closed without merging