Created travis.yml file
ppc64le/build-scripts pull request #423
Opened 2021-01-07 14:28 UTC by rajesh-ibm-power

Created travis.yml file for jetty-reactive-httpclient package

2021-01-20 03:20 UTC, Siddhesh-Ghadi requested changes

2021-01-20 03:20 UTC, Siddhesh-Ghadi commented on travis-ymls/jetty-reactive-httpclient.travis.yml
> +  - export PATH=$M2_HOME/bin:$PATH
We have maven pre- installed in ppc64le image. Please remove this installation. @rajesh-ibm-power

2021-01-29 07:20 UTC, gururajrkatti commented
@rajesh-ibm-power any updates here ?

2021-05-18 04:43 UTC, gururajrkatti commented
@rajesh-ibm-power any updates on this ?

2021-06-23 14:30 UTC, rajesh-ibm-power commented
@gururajrkatti updated dist to bionic .kindly verify

2021-06-29 12:14 UTC, gururajrkatti reviewed
Looks good to me. @Siddhesh-Ghadi I have verified that maven installation has been removed. Do you have any other observations/comments ?

2021-06-29 12:51 UTC, Siddhesh-Ghadi commented
No other changes. @gururajrkatti

2021-08-04 05:08 UTC, merged