Added power support for the travis.yml file with ppc64le.
ppc64le/build-scripts pull request #453
Opened 2021-01-11 09:47 UTC by sreekanth370

Added power support for the travis.yml file with ppc64le. This is part of the Ubuntu distribution for ppc64le. 
This helps us simplify testing later when distributions are re-building and re-releasing.

2021-01-20 06:20 UTC, gururajrkatti requested changes
What is the reason we are excluding jobs from amd ?

2021-01-29 07:22 UTC, gururajrkatti commented
@sreekanth370 any updates on this ?

2021-02-11 06:46 UTC, sreekanth370 commented
Hi Guru ,   may be excluded the jobs for unsupported versions like python 2.6,3.2,3,3and pypy on both amd and ppc .
 kindly look which are failed version .
 https://travis-ci.com/github/sreekanth370/retrying/builds/212651280

2021-02-11 13:08 UTC, gururajrkatti commented
You can exclude for only ppc if it is failing only for ppc

2021-02-11 13:51 UTC, sreekanth370 commented
excluded the  ppc  jobs , which are not support.
amd jobs fails for python 2.6, 3.2 and 3.3 .

2021-02-11 13:52 UTC, sreekanth370 commented
https://travis-ci.com/github/sreekanth370/retrying/builds/216787634

2021-02-12 04:22 UTC, gururajrkatti commented
If you are excluding for both amd and ppc, then you can directly remove those versions. Add a comment with the reason for removing

2021-02-15 05:06 UTC, sreekanth370 commented
updated the PR , kindly check it

2021-02-15 12:28 UTC, gururajrkatti requested changes

2021-02-15 12:28 UTC, gururajrkatti commented on travis-ymls/retrying.py_travis.yml
> +    - arch: amd64
Can we do not do something like below and avoid excluding 2.6, 3.2 and 3.3 for both ?
python:
    - 2.7
    - 3.4
    - 3.5
    - pypy

2021-02-15 12:55 UTC, sreekanth370 commented
unfortunately travis file was deleted .hence closing.

2021-02-15 12:56 UTC, closed without merging