Currency: Created build script and build_info.json for Pyspnego
ppc64le/build-scripts pull request #4583
Opened 2024-10-01 12:43 UTC by aastha-sharma2

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Have you validated script on UBI 9 container
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2024-11-29 06:04 UTC, shubham-dayma-ibm requested changes

2024-11-29 06:04 UTC, shubham-dayma-ibm commented on p/pyspnego/build_info.json
> +  "github_url": "https://github.com/pyca/pyopenssl.git",
Incorrect github_url

2024-11-29 06:04 UTC, shubham-dayma-ibm commented on p/pyspnego/build_info.json
> +  "*.*.*": {
Can't we simply set it "*", why to complicate?

2024-11-29 06:06 UTC, aastha-sharma2 commented on p/pyspnego/build_info.json
> +  "github_url": "https://github.com/pyca/pyopenssl.git",
> Incorrect github_url

rectified.

2024-12-18 08:51 UTC, nikhil-kalbande approved these changes

2024-12-18 08:51 UTC, merged