Currency: Added build scripts and updated build_info.json files for llvmlite
ppc64le/build-scripts pull request #4662
Opened 2024-10-22 12:40 UTC by npanpaliya

## Checklist

- [ ] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [ ] Have you validated script on UBI 9 container
- [ ] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2024-10-23 04:35 UTC, prachikurade1 requested changes

2024-10-23 04:35 UTC, prachikurade1 commented on l/llvmlite/build_info.json
> +   "version": "v0.41.1",
Can add support for latest version - v0.43.0

2024-10-23 04:35 UTC, prachikurade1 commented on l/llvmlite/llvmlite_ubi_9_3.sh
> +deactivate
`deactivate` should be before exit 0.

2024-10-23 04:42 UTC, prachikurade1 commented on l/llvmlite/build_info.json
> +   "version": "v0.41.1",
For currency the latest version is added and if we need a specific version (that does not work with the same script) then we add another script with the required version.
Sample PR - https://github.com/ppc64le/build-scripts/pull/4493

2024-10-25 08:04 UTC, shubham-dayma-ibm requested changes

2024-10-25 08:04 UTC, shubham-dayma-ibm commented on l/llvmlite/build_info.json
> +   "build_script": "llvmlite_v0.41.1_ubi_9_3.sh",
Good to set latest version's build script here(v0.43.0)

2024-10-25 08:41 UTC, nikhil-kalbande requested changes

2024-10-25 08:41 UTC, nikhil-kalbande commented on l/llvmlite/build_info.json
> +   "docker_build": true,
if we are not adding dockerfile.. lets not make docker_build flag true.

2024-10-25 08:41 UTC, nikhil-kalbande commented on l/llvmlite/build_info.json
> +   "*": {
If no docker build support you can remove this whole block  
   "*": {
     "dir": "linux",
      "base_docker_image": "base",
      "base_docker_variant": "Not defined"
   },

2024-10-29 09:58 UTC, ghatwala approved these changes
lgtm

2024-10-29 09:59 UTC, merged