Currency: Added build_info.json and build_script for grpcio
ppc64le/build-scripts pull request #4700
Opened 2024-10-28 12:18 UTC by bhagyashrigai

## Checklist

- [ ] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [ ] Have you validated script on UBI 9 container
- [ ] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2024-11-08 06:15 UTC, shubham-dayma-ibm requested changes

2024-11-08 06:15 UTC, shubham-dayma-ibm commented on g/grpc/grpcio_ubi_9.3.sh
> +PYTHON_VERSION=${2:-3.9}
No need to add `PYTHON_VERSION` variable and python installation instructions in build-scripts. Use just `python` and `pip`, rather using `pip3` or `python3` in your commands. Also avoid creating venvs in build-scripts.
For testing, you can create venv with desire python version in your ssh terminal and test your build-scripts.

2024-11-08 06:15 UTC, shubham-dayma-ibm commented on g/grpc/grpcio_ubi_9.3.sh
> +if ! python -m unittest tests.unit._invalid_metadata_test tests.unit._compression_test; then
Hope this is running entire test suit, rather hitting single unit test.

2024-11-21 10:49 UTC, bhagyashrigai commented on g/grpc/grpcio_ubi_9.3.sh
> +yum install -y python-devel python-pip python-setuptools git cmake autoconf libtool gcc gcc-c++ make openssl-devel zlib-devel libuuid-devel gcc-gfortran
python3.9

2024-11-21 13:48 UTC, merged