Currency: Added build_script and build_info for requires-port.
ppc64le/build-scripts pull request #4704
Opened 2024-10-30 06:17 UTC by ramnathnayak-ibm

…port

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Have you validated script on UBI 9 container
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2025-01-09 10:03 UTC, prachikurade1 requested changes

2025-01-09 10:03 UTC, prachikurade1 commented on r/requires-port/requires-port_ubi_9.3.sh
> +PACKAGE_VERSION=${1:-master}
If adding support for master branch, add the version id as the specific commit. Accordingly update wherever applicable in the build info and the script.

2025-01-13 09:54 UTC, ramnathnayak-ibm commented on r/requires-port/requires-port_ubi_9.3.sh
> +PACKAGE_VERSION=${1:-master}
@prachikurade1 Do you want me to build this package for the last commit?

2025-01-13 09:56 UTC, prachikurade1 commented on r/requires-port/requires-port_ubi_9.3.sh
> +PACKAGE_VERSION=${1:-master}
yes, the last commit in master

2025-01-13 09:57 UTC, prachikurade1 commented on r/requires-port/requires-port_ubi_9.3.sh
> +PACKAGE_VERSION=${1:-master}
You can use this id - 07e8e82

2025-01-13 10:01 UTC, ramnathnayak-ibm commented on r/requires-port/requires-port_ubi_9.3.sh
> +PACKAGE_VERSION=${1:-master}
Ok. Thanks

2025-01-13 10:21 UTC, prachikurade1 approved these changes
Approved

2025-01-13 10:22 UTC, merged