Added build script for onnxruntime v1.20.0 and updated build_info.json
ppc64le/build-scripts pull request #4727
Opened 2024-11-06 09:25 UTC by puneetsharma21

## Checklist

- [ ] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [ ] Have you validated script on UBI 9 container
- [ ] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2024-11-08 06:07 UTC, shubham-dayma-ibm requested changes
@puneetsharma21  We already have build-script of [onnxruntime](https://github.com/ppc64le/build-scripts/blob/master/o/onnxruntime/onnxruntime_ubi_9_3.sh). Have you tried that script with you version? Do we really require new build-script for your version?

2024-11-08 06:07 UTC, shubham-dayma-ibm commented on o/onnxruntime/onnxruntime_v1.20.0_ubi_9_3.sh
> +source myenv/bin/activate
No need to create venv
Use just `python` and `pip`, rather using `python3`, `pip3` or something else, to reduce future reworks

2024-11-08 06:07 UTC, shubham-dayma-ibm commented on o/onnxruntime/onnxruntime_v1.20.0_ubi_9_3.sh
> +yum install -y git gcc-c++ make wget java-11-openjdk-devel  openssl-devel bzip2 zip unzip yum-utils clang clang-devel clang-libs python3.11 python3.11-devel patch
Remove python installation instructions

2024-11-22 05:48 UTC, puneetsharma21 commented on o/onnxruntime/onnxruntime_v1.20.0_ubi_9_3.sh
> +    echo "------------------$PACKAGE_NAME:build_&_test_both_success-------------------------"
@npanpaliya tests are executing here in build.sh file
`./build.sh --allow_running_as_root --compile_no_warning_as_error --config Release`

2024-11-25 08:45 UTC, shubham-dayma-ibm approved these changes
LGTM

2024-11-25 13:12 UTC, merged