Currency: Added build script and build_info for axios.
ppc64le/build-scripts pull request #4777
Opened 2024-11-15 05:46 UTC by ramnathnayak-ibm

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Have you validated script on UBI 9 container
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2025-01-09 10:06 UTC, prachikurade1 requested changes

2025-01-09 10:06 UTC, prachikurade1 commented on a/axios/build_info.json
> +   "version": "v1.7.7",
Latest version is 1.7.9. We need to add latest release support for currency.

2025-01-09 10:06 UTC, prachikurade1 commented on a/axios/build_info.json
> +   "v*.*.*" : {
Use regex v1.*.* to avoid matching other older versions.

2025-01-09 11:35 UTC, prachikurade1 approved these changes
Approved

2025-01-09 11:36 UTC, merged

2025-01-13 09:59 UTC, ramnathnayak-ibm commented on a/axios/build_info.json
> +   "version": "v1.7.7",
Addressed review comments.

2025-01-13 09:59 UTC, ramnathnayak-ibm commented on a/axios/build_info.json
> +   "v*.*.*" : {
Addressed review comments.