Currency : Added build_script and build_info for node-prometheus-gc-stats
ppc64le/build-scripts pull request #4809
Opened 2024-11-20 12:01 UTC by ramnathnayak-ibm

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Have you validated script on UBI 9 container
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2025-01-09 10:09 UTC, prachikurade1 requested changes

2025-01-09 10:09 UTC, prachikurade1 commented on n/node-prometheus-gc-stats/build_info.json
> +   "v*.*.*" : {
Make version specific `v1.*.*`.

2025-01-09 11:38 UTC, prachikurade1 approved these changes
Approved

2025-01-09 11:38 UTC, merged

2025-01-13 09:59 UTC, ramnathnayak-ibm commented on n/node-prometheus-gc-stats/build_info.json
> +   "v*.*.*" : {
Addressed review comments.