Currency:Added build-script,build_info.json for meta-types
ppc64le/build-scripts pull request #4831
Opened 2024-11-26 07:01 UTC by vinodk99

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Have you validated script on UBI 9 container
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2025-01-08 10:39 UTC, nikhil-kalbande approved these changes

2025-01-09 16:22 UTC, prachikurade1 requested changes

2025-01-09 16:22 UTC, prachikurade1 commented on m/meta-types/build_info.json
> +  "v*.*.*": {
Version regex should be `v2.*.*`

2025-01-10 05:56 UTC, vinodk99 commented on m/meta-types/build_info.json
> +  "v*.*.*": {
@prachikurade1 addressed review comments

2025-01-10 06:19 UTC, prachikurade1 approved these changes
Approved

2025-01-10 06:19 UTC, merged