Currency: Added build_script and build_info for node-ignore.
ppc64le/build-scripts pull request #4838
Opened 2024-11-27 06:26 UTC by ramnathnayak-ibm

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Have you validated script on UBI 9 container
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2025-01-09 10:11 UTC, prachikurade1 requested changes

2025-01-09 10:11 UTC, prachikurade1 commented on n/node-ignore/build_info.json
> +   "version": "6.0.1",
Latest version is 7.0.0. Need to add latest version support for currency.

2025-01-09 10:11 UTC, prachikurade1 commented on n/node-ignore/build_info.json
> +   "*.*.*" : {
Version regex should be specific to the version which support you have tested for the script.

2025-01-09 11:37 UTC, prachikurade1 approved these changes
Approved

2025-01-09 11:37 UTC, merged

2025-01-13 10:00 UTC, ramnathnayak-ibm commented on n/node-ignore/build_info.json
> +   "version": "6.0.1",
Updated the file.

2025-01-13 10:00 UTC, ramnathnayak-ibm commented on n/node-ignore/build_info.json
> +   "*.*.*" : {
Addressed review comments.