Currency: Updated build script and build_info.json for LightGBM
ppc64le/build-scripts pull request #4852
Opened 2024-11-28 14:48 UTC by aastha-sharma2

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Have you validated script on UBI 9 container
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2024-11-29 06:27 UTC, shubham-dayma-ibm requested changes
PR status is Draft, still reviewed it. Also missing license file

2024-11-29 06:27 UTC, shubham-dayma-ibm commented on l/lightGBM/lightGBM_ubi_9.3.sh
> +        python3 setup.py build
Why building instructions?

2024-12-06 06:45 UTC, shubham-dayma-ibm requested changes

2024-12-06 06:45 UTC, shubham-dayma-ibm commented on l/lightGBM/lightGBM_ubi_9.3.sh
> +    exit
It should be `exit 1`

2024-12-06 10:24 UTC, aastha-sharma2 commented on l/lightGBM/lightGBM_ubi_9.3.sh
> +    exit
> It should be `exit 1`

Updated.

2024-12-18 08:49 UTC, nikhil-kalbande approved these changes

2024-12-18 08:49 UTC, merged