Currency:Added build-script,build_info.json for node-xml-encryption
ppc64le/build-scripts pull request #4853
Opened 2024-11-29 05:58 UTC by vinodk99

## Checklist

- [x] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [x] Have you validated script on UBI 9 container
- [x] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2025-01-09 16:23 UTC, prachikurade1 requested changes

2025-01-09 16:23 UTC, prachikurade1 commented on n/node-xml-encryption/build_info.json
> +    "v*.*.*": {
Version regex should be `v2.*.*`

2025-01-10 05:59 UTC, vinodk99 commented on n/node-xml-encryption/build_info.json
> +    "v*.*.*": {
@prachikurade1 addressed review comments

2025-01-10 06:19 UTC, prachikurade1 approved these changes
Approved

2025-01-10 06:19 UTC, merged