Currency: Created build script and build_info.json for Dask 2.20.0
ppc64le/build-scripts pull request #4884
Opened 2024-12-05 08:40 UTC by rakshithr5

## Checklist

- [ ] Have you checked and followed all the points mention in the [CONTRIBUTING.MD](https://github.com/ppc64le/build-scripts/blob/master/CONTRIBUTING.md)
- [ ] Have you validated script on UBI 9 container
- [ ] Did you run the script(s) on fresh container with `set -e` option enabled and observe success ?
- [ ] Did you have **Legal approvals** for patch files ?

2024-12-05 09:13 UTC, shubham-dayma-ibm requested changes

2024-12-05 09:13 UTC, shubham-dayma-ibm commented on d/dask/dask_ubi_9.3.sh
> +if ! python3 setup.py install; then
Why we are installation packages two types?

2024-12-05 09:13 UTC, shubham-dayma-ibm commented on d/dask/dask_ubi_9.3.sh
> +if ! pytest --disable-warnings; then
I don't see else block where it says "Both_Install_and_Test_Success" and exist 0

2024-12-05 09:13 UTC, shubham-dayma-ibm commented on d/dask/dask_ubi_9.3.sh
> +    exit 0
It should be  `exit 2` here, if tests are failing.

2025-01-01 06:26 UTC, nikhil-kalbande approved these changes

2025-01-01 06:26 UTC, merged