Create json-flattener.travis.yml
ppc64le/build-scripts pull request #498
Opened 2021-01-17 15:03 UTC by nageshlop

Added support for ppc64le and created .travis.yml file, updated pom.xml file for resolving the build and test issues.

2021-01-18 12:10 UTC, Siddhesh-Ghadi requested changes

2021-01-18 12:10 UTC, Siddhesh-Ghadi commented on travis-ymls/json-flattener.travis.yml
> +      - maven
```suggestion
```
We have maven pre-installed. No need to install it again.

2021-01-19 05:51 UTC, nageshlop commented
As per the inputs have removed apt mvn install lines as it is preinstalled. Verified the build and test with latest changes.

2021-01-19 12:09 UTC, Siddhesh-Ghadi commented
Ready for merge @seth-priya

2021-01-19 13:48 UTC, merged