Currency: Added build_script and build_info.json for ruamel.yaml.clib
ppc64le/build-scripts pull request #5075
Opened 2024-12-23 16:05 UTC by shubham-dayma-ibm

Adding build_script and build_info.json

2024-12-24 09:52 UTC, nikhil-kalbande commented
@shubham-dayma-ibm We wont be able to add this to currency as it uses non github source

2024-12-24 09:53 UTC, nikhil-kalbande requested changes

2024-12-24 09:53 UTC, nikhil-kalbande commented on r/ruamel.yaml.clib/ruamel.yaml.clib_ubi_9.3.sh
> +PACKAGE_URL=https://pypi.io/packages/source/r/ruamel.yaml.clib/ruamel.yaml.clib-0.2.6.tar.gz
Currency currently doesn't support non GitHub source

2025-01-08 09:36 UTC, shubham-dayma-ibm reviewed
@aastha-sharma2 can't see build_info.json

2025-01-08 10:04 UTC, merged