Create jquery-trap-input.travis.yml
ppc64le/build-scripts pull request #508
Opened 2021-01-18 11:36 UTC by gururajrkatti

2021-01-18 11:50 UTC, Siddhesh-Ghadi commented
Since the `travis.yml` is created from scratch, should we also test it on `latest` and `lts` node versions or stick to one specfied in build-script? @seth-priya 

Rest all looks good.

2021-01-21 07:54 UTC, seth-priya commented
yes, testing with latest versions make sense @Siddhesh-Ghadi

2021-01-22 05:36 UTC, Siddhesh-Ghadi requested changes
For all node `.travis.yml` which we create from scratch, lets test them on latest node versions also.

2021-01-22 05:36 UTC, Siddhesh-Ghadi commented on travis-ymls/jquery-trap-input.travis.yml
> +nodejs: 10
```suggestion
nodejs: 
    - 10
    - node  #latest stable Node.js release
    - lts/* #latest LTS Node.js release
```

2021-01-22 06:32 UTC, gururajrkatti commented
Thanks @Siddhesh-Ghadi, incorporated your changes, tested on travis, updated the travis log location in the file and squashed the commits.

2021-01-22 11:40 UTC, Siddhesh-Ghadi commented
Ready for merge @seth-priya

2021-01-22 11:51 UTC, merged