Create zope.interface.travis.yml
ppc64le/build-scripts pull request #518
Opened 2021-01-19 15:19 UTC by genisysram

2021-01-20 09:38 UTC, gururajrkatti requested changes
You have added "arch:" and "jobs: exclude" when there is already "jobs: include". This has completely changed the different jobs that are running in current build and your build. Pl. correct it. I think you need to add everything in existing "jobs:"

2021-02-03 12:21 UTC, gururajrkatti commented
@genisysram any updates on this ?

2021-02-24 04:02 UTC, genisysram commented
The Tests with **Macos** were failing, and I have raised the same in the community , they find some issue and considered for enchancements for future.
https://github.com/zopefoundation/meta/issues/63

2021-02-24 04:24 UTC, gururajrkatti commented on travis-ymls/zope.interface.travis.yml
> +    - name: Documentation
I think you can include this also for ppc64le ?

2021-02-24 04:25 UTC, gururajrkatti commented on travis-ymls/zope.interface.travis.yml
> +    # manylinux wheel builds
I think you can include this also for ppc64le

2021-02-24 04:25 UTC, gururajrkatti commented on travis-ymls/zope.interface.travis.yml
> +      python: 2.7
What is the reason for excluding this version ?

2021-03-03 10:55 UTC, genisysram commented
@gururajrkatti 
updated all the suggested changes , Macos are failing with known issues.

2021-03-03 12:13 UTC, gururajrkatti reviewed
Pl. squash the commits

2021-03-03 12:13 UTC, gururajrkatti commented on travis-ymls/zope.interface.travis.yml
> +    - name: aarch64 wheels
I think this is specific to arm64 and not needed.

2021-03-03 14:44 UTC, genisysram commented
@gururajrkatti 
updated as per comments

2021-03-04 08:01 UTC, gururajrkatti approved these changes
LGTM

2021-03-04 09:27 UTC, merged