Created travis.yml for package tar
ppc64le/build-scripts pull request #547
Opened 2021-01-22 07:09 UTC by rajesh-ibm-power

Created travis.yml for package tar node

2021-01-22 12:04 UTC, Siddhesh-Ghadi requested changes

2021-01-22 12:04 UTC, Siddhesh-Ghadi commented on travis-ymls/tar.travis.yml
> +   - 10
https://github.com/ppc64le/build-scripts/pull/508#discussion_r562398080

2021-02-15 11:08 UTC, rajesh-ibm-power commented
@Siddhesh-Ghadi
Updated with node and lts/*, kindly review and merge

2021-02-16 15:02 UTC, Siddhesh-Ghadi commented
Ready for merge @seth-priya

2021-02-17 15:40 UTC, merged