Create rxJava.travis.yml
ppc64le/build-scripts pull request #751
Opened 2021-03-04 10:10 UTC by genisysram

2021-03-04 11:06 UTC, gururajrkatti requested changes
command in the script doesn't seem to be doing anything. Pl. check

2021-03-04 16:11 UTC, genisysram commented
@gururajrkatti 
Modified the code.

2021-03-09 12:19 UTC, gururajrkatti commented on travis-ymls/rxJava.travis.yml
> +    - ./gradlew
You are still using just this command. I think it's not doing anything as per logs.

2021-03-10 10:07 UTC, genisysram commented
@gururajrkatti 
Modified the code

2021-03-11 04:22 UTC, gururajrkatti approved these changes
ok

2021-03-15 02:33 UTC, merged