Create microprofile-config.travis.yml
ppc64le/build-scripts pull request #792
Opened 2021-03-24 11:58 UTC by nagesh4193

2021-03-29 12:13 UTC, gururajrkatti commented
Do we have build_script available for this ?

2021-04-08 13:48 UTC, nagesh4193 commented
I have added build script for microprofile-config and the success message in my local vm as below:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] MicroProfile Config ................................ SUCCESS [ 13.330 s]
[INFO] MicroProfile Config Specification .................. SUCCESS [ 37.136 s]
[INFO] MicroProfile Config API ............................ SUCCESS [ 16.860 s]
[INFO] MicroProfile Config TCK ............................ SUCCESS [ 13.852 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:23 min
[INFO] Finished at: 2021-04-08T13:34:20+00:00
[INFO] Final Memory: 125M/450M
[INFO] ------------------------------------------------------------------------

2021-04-16 06:59 UTC, gururajrkatti requested changes

2021-04-16 06:59 UTC, gururajrkatti commented on m/microprofile-config/microprofile-config_ubuntu_16.04.sh
> +git clone https://github.com/eclipse/microprofile-config
Pl. have the version number passed as an argument along with the default one used in the script as mentioned earlier. Also upload the LICENSE file

2021-07-26 04:55 UTC, nagesh4193 commented
This is failing when version is added in the build specification, so I am closing this PR and would raise a new PR after the fix.

2021-07-26 04:55 UTC, closed without merging