AddPowerSupport_python-memcached
ppc64le/build-scripts pull request #799
Opened 2021-03-26 08:32 UTC by santosh653

Creating python-memcached.travis.yml with proposed changes.

2021-03-26 10:23 UTC, gururajrkatti requested changes

2021-03-26 10:23 UTC, gururajrkatti commented on travis-ymls/python-memcached.travis.yml
> +  - python -m pip install flake8
whats the reason "pip install -r test-requirements.txt" from original file removed ?

2021-04-20 06:38 UTC, gururajrkatti commented
@santosh653 any updates on this

2021-07-02 12:54 UTC, gururajrkatti commented
@santosh653 any updates on this ?

2021-08-24 06:36 UTC, gururajrkatti commented
@santosh653 can you pl. revert on this

2021-09-30 05:38 UTC, gururajrkatti commented
@santosh653 any updates on this

2021-11-18 05:47 UTC, santosh653 commented
closing this PR.

2021-11-18 05:47 UTC, closed without merging