Santosh royal compiler
ppc64le/build-scripts pull request #830
Opened 2021-04-16 09:44 UTC by santosh653

[INFO] Reactor Summary for Apache Royale: Compiler: Parent 0.9.8:
[INFO]
[INFO] Apache Royale: Compiler: Parent .................... SUCCESS [ 28.378 s]
[INFO] Apache Royale: Compiler: Compiler-Common ........... SUCCESS [ 14.242 s]
[INFO] Apache Royale: Compiler: Test Utils ................ SUCCESS [  1.836 s]
[INFO] Apache Royale: Compiler: Externc ................... SUCCESS [ 26.527 s]
[INFO] compiler-playerglobalc ............................. SUCCESS [  2.082 s]
[INFO] Apache Royale: Compiler: Compiler .................. SUCCESS [01:07 min]
[INFO] Apache Royale: Compiler: Compiler-JX ............... SUCCESS [01:11 min]
[INFO] Apache Royale: Compiler: SWFUtils .................. SUCCESS [  1.527 s]
[INFO] Apache Royale: Compiler: Debugger .................. SUCCESS [  4.554 s]
[INFO] Apache Royale: Compiler: OEM Layer ................. SUCCESS [  3.068 s]
[INFO] Apache Royale: Royale Ant Tasks .................... SUCCESS [  1.244 s]
[INFO] Apache Royale: RoyaleUnit Ant Tasks ................ SUCCESS [  1.635 s]
[INFO] Apache Royale: Royale Maven Plugin ................. SUCCESS [  9.208 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:56 min
[INFO] Finished at: 2021-04-16T08:00:13Z
[INFO] ------------------------------------------------------------------------
ubuntu@santoshkulkarni:~/royale-compiler$ chmod 777 royale-compiler_ubuntu_20.04.sh

2021-04-19 10:12 UTC, gururajrkatti requested changes
Pl. add the LICENSE file

2021-04-20 10:33 UTC, santosh653 commented
@gururajrkatti I have added License File.

2021-04-21 07:09 UTC, gururajrkatti approved these changes
LGTM

2021-04-22 07:13 UTC, seth-priya approved these changes

2021-04-22 07:13 UTC, merged