Add files via upload
ppc64le/build-scripts pull request #856
Opened 2021-04-27 10:48 UTC by mohitp333

Added built script for empty

2021-04-27 11:42 UTC, seth-priya commented
@Ryan-Dmello please review

2021-04-28 08:44 UTC, Ryan-Dmello commented
File naming convention is not matching with distro its verified on(as per doc string in the script). Please change the script name to empty_rhel_8.3.sh(if tested on RHEL 8.3)

2021-04-28 08:44 UTC, Ryan-Dmello requested changes

2021-04-28 08:44 UTC, Ryan-Dmello commented on e/empty/empty_rhel_7.6.sh.txt
> +# npm install -g yarn
Please remove commented lines

2021-04-28 08:44 UTC, Ryan-Dmello commented on e/empty/empty_rhel_7.6.sh.txt
> +# Node Version  : v10.24.0
Please mention package version also

2021-04-28 08:44 UTC, Ryan-Dmello commented on e/empty/empty_rhel_7.6.sh.txt
> +yum -y update
if installation is required(i.e root), please mention that in script documentation

2021-05-26 05:39 UTC, seth-priya commented
@mohitp333 any update on this?

2021-08-10 08:59 UTC, seth-priya commented
@Ryan-Dmello please review

2021-08-10 10:40 UTC, Ryan-Dmello commented
@seth-priya, the previous review comments are still not incorporated/justified yet. I have no new review comments other than the once i already mentioned above

2021-10-08 05:22 UTC, seth-priya commented
@mohitp333 any update on this?

2021-10-08 05:54 UTC, mohitp333 commented
Hi Priya,
 
Sorry for delay in update can I get sometime, I am just verifying it once.
----- Original message -----From: "Priya Seth" ***@***.***>To: "ppc64le/build-scripts" ***@***.***>Cc: "mohitp333" ***@***.***>, "Mention" ***@***.***>Subject: [EXTERNAL] Re: [ppc64le/build-scripts] Add files via upload (#856)Date: Fri, Oct 8, 2021 10:52 AM      @mohitp333 any update on this? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍    ZjQcmQRYFpfptBannerStart  

This Message Is From an External Sender
This message came from outside your organization. ZjQcmQRYFpfptBannerEnd 
 
@mohitp333 any update on this?
—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. 
 

2021-11-26 09:23 UTC, seth-priya commented
@Ryan-Dmello please review and confirm

2021-11-26 11:44 UTC, Ryan-Dmello commented
Doc string is missing Package name section. Also the package version is set to master. @mohitp333 Please verify and make changes as required

2021-11-26 11:57 UTC, Ryan-Dmello commented
Changes look ok

2021-11-26 12:10 UTC, merged