Create egeria_ubuntu_20.04.sh
ppc64le/build-scripts pull request #870
Opened 2021-05-04 14:20 UTC by nageshlop

Created build script and verified the working of build and test on local VM.

2021-05-04 14:23 UTC, nageshlop commented
Build and test logs:
[INFO]      [java] 06:15:29.440 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/ReferenceableToIncidentReport/ResultingIncidentReportsReference.java
[INFO]      [java] 06:15:29.442 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/IncidentReportToReferenceable/OriginatorsReference.java
[INFO]      [java] 06:15:29.444 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/ReferenceableToInformalTag/TagsReference.java
[INFO]      [java] 06:15:29.446 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/InformalTagToReferenceable/TaggedElementReference.java
[INFO]      [java] 06:15:29.448 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/GlossaryTermToGlossaryTerm/AttributesReference.java
[INFO]      [java] 06:15:29.451 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/GlossaryTermToGlossaryTerm/ObjectsReference.java
[INFO]      [java] 06:15:29.454 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/ToDoToReferenceable/ElementsToWorkOnReference.java
[INFO]      [java] 06:15:29.456 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/ReferenceableToToDo/IdentifiedToDoActionsReference.java
[INFO]      [java] 06:15:29.458 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/GovernanceDriverToGovernancePolicy/PoliciesReference.java
[INFO]      [java] 06:15:29.460 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/GovernancePolicyToGovernanceDriver/DriversReference.java
[INFO]      [java] 06:15:29.462 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/SolutionComponentToSolutionPort/SolutionPortsReference.java
[INFO]      [java] 06:15:29.465 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/SolutionPortToSolutionComponent/SolutionComponentReference.java
[INFO]      [java] 06:15:29.467 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/ValidValueDefinitionToValidValueDefinition/MatchingValueReference.java
[INFO]      [java] 06:15:29.470 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/DataProfileLogAnnotationToLogFile/DataProfileLogFilesReference.java
[INFO]      [java] 06:15:29.472 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/LogFileToDataProfileLogAnnotation/DataProfileAnnotationsReference.java
[INFO]      [java] 06:15:29.474 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/ReferenceableToIncidentReport/IncidentReportsReference.java
[INFO]      [java] 06:15:29.476 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/IncidentReportToReferenceable/ImpactedResourcesReference.java
[INFO]      [java] 06:15:29.478 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/ReferenceableToPersonRole/GovernedByRolesReference.java
[INFO]      [java] 06:15:29.480 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/PersonRoleToReferenceable/GovernanceAssignmentsReference.java
[INFO]      [java] 06:15:29.482 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/AssetToOpenDiscoveryAnalysisReport/AssetDiscoveryAnalysisReportsReference.java
[INFO]      [java] 06:15:29.484 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/OpenDiscoveryAnalysisReportToAsset/DiscoveryReportTargetReference.java
[INFO]      [java] 06:15:29.485 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/ReferenceableToLike/LikesReference.java
[INFO]      [java] 06:15:29.487 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/LikeToReferenceable/LikeAnchorReference.java
[INFO]      [java] 06:15:29.490 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/NoteLogAuthorToNoteLog/AuthoredNoteLogsReference.java
[INFO]      [java] 06:15:29.491 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/op [...]

2021-05-05 07:36 UTC, gururajrkatti requested changes

2021-05-05 07:36 UTC, gururajrkatti commented on e/egeria/egeria_ubuntu_20.04.sh
> +sudo mvn test -B
Isn't "mvn test' going to be covered by "mvn install" (previous step) ? What is the jar file its going to build ?

2021-05-05 07:36 UTC, gururajrkatti commented on e/egeria/egeria_ubuntu_20.04.sh
> +# Version       : master
Pl. mention the current version being tested since "master" keeps moving

2021-05-07 12:08 UTC, gururajrkatti commented on e/egeria/egeria_ubuntu_20.04.sh
> +sudo mvn test -B
Did not hear back on the above comment "Isn't "mvn test' going to be covered by "mvn install" (previous step) ? What is the jar file its going to build ?"

2021-05-17 07:21 UTC, nageshlop commented
@gururajrkatti and @seth-priya let me know if any changes required.

2021-05-17 11:01 UTC, gururajrkatti commented
@nageshlop I couldn't see any package dataenginetests in the WKC jar list, which sheet/row does this script correspond to ?

2021-05-18 05:17 UTC, nageshlop commented
@gururajrkatti I am working on below package as part of this other related jars get generated.
97 data-engine-api-1.1.20190923.jar 1.1.201909 https://github.com/odpi/egeria

2021-05-18 05:32 UTC, nageshlop commented
@gururajrkatti  closing all related and dependent packages build script. As discussed will be creating single script to take argument as package name, and run the build and update the respective jar file details.

2021-05-18 05:32 UTC, closed without merging