Create xmlenc_20.04.sh
ppc64le/build-scripts pull request #892
Opened 2021-05-17 05:47 UTC by gururajrkatti

1. Default execution:
ubuntu@gururaj:~/guru$ ./xmlenc_20.04.sh
Ign:1 http://binaries.erlang-solutions.com/debian focal InRelease
Hit:2 http://binaries.erlang-solutions.com/debian focal Release
Ign:3 https://dl.bintray.com/sbt/debian  InRelease
Get:4 https://dl.bintray.com/sbt/debian  Release [815 B]
Hit:6 http://ports.ubuntu.com/ubuntu-ports focal InRelease
Hit:7 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
Hit:9 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty InRelease
Hit:10 https://packages.microsoft.com/ubuntu/14.04/prod trusty InRelease
Hit:11 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
Hit:12 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb focal InRelease
Hit:13 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
Hit:14 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu focal InRelease
Hit:15 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal InRelease
Fetched 815 B in 1s (732 B/s)
Reading package lists... Done
N: Skipping acquire of configured file 'contrib/binary-ppc64el/Packages' as repository 'http://binaries.erlang-solutions.com/debian focal InRelease' doesn't support architecture 'ppc64el'
Reading package lists... Done
Building dependency tree
Reading state information... Done
wget is already the newest version (1.20.3-1ubuntu1).
git is already the newest version (1:2.25.1-1ubuntu3.1).
openjdk-8-jdk is already the newest version (8u292-b10-0ubuntu1~20.04).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 linux-headers-5.4.0-73-generic : Depends: linux-headers-5.4.0-73 but it is not going to be installed
 linux-image-virtual : Depends: linux-image-5.4.0-73-generic but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
--2021-05-17 05:43:19--  http://www-eu.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
Resolving www-eu.apache.org (www-eu.apache.org)... 95.216.26.30, 2a01:4f9:2a:1a61::2
Connecting to www-eu.apache.org (www-eu.apache.org)|95.216.26.30|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz [following]
--2021-05-17 05:43:19--  https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
Resolving downloads.apache.org (downloads.apache.org)... 135.181.214.104, 135.181.209.10, 88.99.95.219, ...
Connecting to downloads.apache.org (downloads.apache.org)|135.181.214.104|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9506321 (9.1M) [application/x-gzip]
Saving to: ‘apache-maven-3.6.3-bin.tar.gz.8’

apache-maven-3.6.3-bin.tar. 100%[==========================================>]   9.07M  5.28MB/s    in 1.7s

2021-05-17 05:43:22 (5.28 MB/s) - ‘apache-maven-3.6.3-bin.tar.gz.8’ saved [9506321/9506321]

apache-maven-3.6.3/README.txt
apache-maven-3.6.3/LICENSE
apache-maven-3.6.3/NOTICE
apache-maven-3.6.3/lib/
apache-maven-3.6.3/lib/cdi-api.license
apache-maven-3.6.3/lib/commons-cli.license
apache-maven-3.6.3/lib/commons-io.license
apache-maven-3.6.3/lib/commons-lang3.license
apache-maven-3.6.3/lib/guava.license
apache-maven-3.6.3/lib/guice.license
apache-maven-3.6.3/lib/jansi.license
apache-maven-3.6.3/lib/javax.inject.license
apache-maven-3.6.3/lib/jcl-over-slf4j.license
apache-maven-3.6.3/lib/jsoup.license
apache-maven-3.6.3/lib/jsr250-api.license
apache-maven-3.6.3/lib/org.eclipse.sisu.inject.license
apache-maven-3.6.3/lib/org.eclipse.sisu.plexus.license
apache-maven-3.6.3/lib/plexus-cipher.license
apache-maven-3.6.3/lib/plexus-component-annotations.license
apache-maven-3.6.3/lib/plexus-interpolation.license
apache-maven-3.6.3/lib/plexus-sec-dispatcher.license
apache-maven-3.6.3/lib/plexus-utils.license
apache-maven-3.6.3/lib/slf4j-api.license
apache-maven-3.6.3/boot/
apache-maven-3.6.3/boot/plexus-classworlds.license
apache-maven-3.6.3/lib/jansi-native/
apache-maven-3.6.3/lib/jansi-native/freebsd32/
apache-maven-3.6.3/lib/jansi-native/freebsd64/
apache-maven-3.6.3/lib/jansi-native/linux32/
apache-maven-3.6.3/lib/jansi-native/linux64/
apache-maven-3.6.3/lib/jansi-native/osx/
apache-maven-3.6.3/lib/jansi-native/windows32/
apache-maven-3.6.3/lib/jansi-native/windows64/
apache-maven-3.6.3/lib/jansi-native/freebsd32/libjansi.so
apache-maven-3.6.3/lib/jansi-native/freebsd64/libjansi.so
apache-maven-3.6.3/lib/jansi-native/linux32/libjansi.so
apache-maven-3.6.3/lib/jansi-native/linux64/libjansi.so
apache-maven-3.6.3/lib/jansi-native/osx/libjansi.jnilib
apache-maven-3.6.3/lib/jansi-native/windows32/jansi.dll
apache-maven-3.6.3/lib/jansi-native/windows64/jansi.dll
apache-maven-3.6.3/bin/m2.conf
apache-maven-3.6.3/bin/mvn.cmd
apache-maven-3.6.3/bin/mvnDebug.cmd
apache-maven-3.6.3/bin/mvn
apache-maven-3.6.3/bin/mvnDebug
apache-maven-3.6.3/bin/mvnyjp
apache-maven-3.6.3/conf/
apache-maven-3.6.3/conf/logging/
apache-maven-3.6.3/conf/logging/simplelogger.properties
apache-maven-3.6.3/conf/settings.xml
apache-maven-3.6.3/conf/toolchains.xml
apache-maven-3.6.3/lib/ext/
apache-maven-3.6.3/lib/jansi-native/
apache-maven-3.6.3/lib/ext/README.txt
apache-maven-3.6.3/lib/jansi-native/README.txt
apache-maven-3.6.3/boot/plexus-classworlds-2.6.0.jar
apache-maven-3.6.3/lib/maven-embedder-3.6.3.jar
apache-maven-3.6.3/lib/maven-settings-3.6.3.jar
apache-maven-3.6.3/lib/maven-settings-builder-3.6.3.jar
apache-maven-3.6.3/lib/maven-plugin-api-3.6.3.jar
apache-maven-3.6.3/lib/maven-model-3.6.3.jar
apache-maven-3.6.3/lib/maven-model-builder-3.6.3.jar
apache-maven-3.6.3/lib/maven-builder-support-3.6.3.jar
apache-maven-3.6.3/lib/maven-resolver-api-1.4.1.jar
apache-maven-3.6.3/lib/maven-resolver-util-1.4.1.jar
apache-maven-3.6.3/lib/maven-shared-utils-3.2.1.jar
apache-maven-3.6.3/lib/commons-io-2.5.jar
apache-maven-3.6.3/lib/guice-4.2.1-no_aop.jar
apache-maven-3.6.3/lib/guava-25.1-android.jar
apache-maven-3.6.3/lib/javax.inject-1.jar
apache-maven-3.6.3/lib/jsr250-api-1.0.jar
apache-maven-3.6.3/lib/plexus-utils-3.2.1.jar
apache-maven-3.6.3/lib/plexus-sec-dispatcher-1.4.jar
apache-maven-3.6.3/lib/plexus-cipher-1.7.jar
apache-maven-3.6.3/lib/slf4j-api-1.7.29.jar
apache-maven-3.6.3/lib/commons-lang3-3.8.1.jar
apache-maven-3.6.3/lib/maven-core-3.6.3.jar
apache-maven-3.6.3/lib/maven-repository-metadata-3.6.3.jar
apache-maven-3.6.3/lib/maven-artifact-3.6.3.jar
apache-maven-3.6.3/lib/maven-resolver-provider-3.6.3.jar
apache-maven-3.6.3/lib/maven-resolver-impl-1.4.1.jar
apache-maven-3.6.3/lib/maven-resolver-spi-1.4.1.jar
apache-maven-3.6.3/lib/org.eclipse.sisu.inject-0.3.4.jar
apache-maven-3.6.3/lib/plexus-component-annotations-2.1.0.jar
apache-maven-3.6.3/lib/maven-compat-3.6.3.jar
apache-maven-3.6.3/lib/plexus-interpolation-1.25.jar
apache-maven-3.6.3/lib/wagon-provider-api-3.3.4.jar
apache-maven-3.6.3/lib/org.eclipse.sisu.plexus-0.3.4.jar
apache-maven-3.6.3/lib/cdi-api-1.0.jar
apache-maven-3.6.3/lib/commons-cli-1.4.jar
apache-maven-3.6.3/lib/wagon-http-3.3.4-shaded.jar
apache-maven-3.6.3/lib/jsoup-1.12.1.jar
apache-maven-3.6.3/lib/jcl-over-slf4j-1.7.29.jar
apache-maven-3.6.3/lib/wagon-file-3.3.4.jar
apache-maven-3.6.3/lib/maven-resolver-connector-basic-1.4.1.jar
apache-maven-3.6.3/lib/maven-resolver-transport-wagon-1.4.1.jar
apache-maven-3.6.3/lib/maven-slf4j-provider-3.6.3.jar
apache-maven-3.6.3/lib/jansi-1.17.1.jar
Cloning into 'xmlenc'...
remote: Enumerating objects: 593, done.
remote: Total 593 (delta 0), reused 0 (delta 0), pack-reused 593
Receiving objects: 100% (593/593), 143.78 KiB | 822.00 KiB/s, done.
Resolving deltas: 100% (263/263), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
 found to checkout
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------------< org.znerd:xmlenc >--------------------------
[INFO] Building XMLenc 0.54-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[ [...]

2021-05-26 05:35 UTC, seth-priya requested changes

2021-05-26 05:35 UTC, seth-priya commented on x/xmlenc/xmlenc_20.04.sh
> +wget http://www-eu.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6                               .3-bin.tar.gz
there seems to be some extraneous space here?

2021-06-17 03:42 UTC, seth-priya commented
@gururajrkatti updates on this?

2021-06-17 06:20 UTC, gururajrkatti commented
Closing it since this package already exists in IBM

2021-06-17 06:20 UTC, closed without merging