Create virtualization-services-server_ubuntu_20.04.sh
ppc64le/build-scripts pull request #916
Opened 2021-05-27 05:01 UTC by nageshlop

Created build script and verified the changes.

2021-05-27 05:10 UTC, nageshlop commented
Build logs:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO]
[INFO] -----------< org.odpi.egeria:virtualization-services-server >-----------
[INFO] Building Virtualization Services Server-side 2.10-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M3:display-info (display-info) @ virtualization-services-server ---
[INFO] Maven Version: 3.6.3
[INFO] JDK Version: 11.0.11 normalized as: 11.0.11
[INFO] OS Info: Arch: ppc64le Family: unix Name: linux Version: 5.4.0-42-generic
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-versions) @ virtualization-services-server ---
[INFO]
[INFO] --- apache-rat-plugin:0.13:check (rat-check) @ virtualization-services-server ---
[INFO] Added 3 additional default licenses.
[INFO] Enabled default license matchers.
[INFO] Added 2 custom approved licenses.
[INFO] Will parse SCM ignores for exclusions...
[INFO] Finished adding exclusions from SCM ignore files.
[INFO] 62 implicit excludes (use -debug for more details).
[INFO] 46 explicit excludes (use -debug for more details).
[INFO] 4 resources included (use -debug for more details)
[INFO] Rat check: Summary over all files. Unapproved: 0, unknown: 0, generated: 0, approved: 4 licenses.
[INFO]
[INFO] --- lombok-maven-plugin:1.18.20.0:delombok (delombok) @ virtualization-services-server ---
[INFO] Delombok complete.
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ virtualization-services-server ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] skip non existing resourceDirectory /scratch/jar-proj/maven-rep/egeria/open-metadata-implementation/governance-servers/virtualization-services/virtualization-services-server/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ virtualization-services-server ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /scratch/jar-proj/maven-rep/egeria/open-metadata-implementation/governance-servers/virtualization-services/virtualization-services-server/target/classes
[INFO]
[INFO] --- maven-clean-plugin:3.1.0:clean (delombok-removal) @ virtualization-services-server ---
[INFO] Deleting /scratch/jar-proj/maven-rep/egeria/open-metadata-implementation/governance-servers/virtualization-services/virtualization-services-server/target/delombok (includes = [], excludes = [])
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:testResources (default-testResources) @ virtualization-services-server ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] skip non existing resourceDirectory /scratch/jar-proj/maven-rep/egeria/open-metadata-implementation/governance-servers/virtualization-services/virtualization-services-server/src/test/resources
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.6:prepare-agent (agent) @ virtualization-services-server ---
[INFO] argLine set to -javaagent:/home/ubuntu/.m2/repository/org/jacoco/org.jacoco.agent/0.8.6/org.jacoco.agent-0.8.6-runtime.jar=destfile=/scratch/jar-proj/maven-rep/egeria/open-metadata-implementation/governance-servers/virtualization-services/virtualization-services-server/target/jacoco.exec
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ virtualization-services-server ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ virtualization-services-server ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:3.2.0:jar (default-jar) @ virtualization-services-server ---
[INFO] Building jar: /scratch/jar-proj/maven-rep/egeria/open-metadata-implementation/governance-servers/virtualization-services/virtualization-services-server/target/virtualization-services-server-2.10-SNAPSHOT.jar
[INFO]
[INFO] --- maven-source-plugin:3.2.1:jar-no-fork (attach-sources) @ virtualization-services-server ---
[INFO] Building jar: /scratch/jar-proj/maven-rep/egeria/open-metadata-implementation/governance-servers/virtualization-services/virtualization-services-server/target/virtualization-services-server-2.10-SNAPSHOT-sources.jar
[INFO]
[INFO] --- maven-javadoc-plugin:3.2.0:jar (attach-javadocs) @ virtualization-services-server ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:05 min
[INFO] Finished at: 2021-05-13T16:03:44Z
[INFO] ------------------------------------------------------------------------
ubuntu@nagesh-at:/scratch/jar-proj/maven-rep/egeria/open-metadata-implementation/governance-servers/virtualization-services/virtualization-services-server$ ls target/
classes            javadoc-bundle-options  maven-status  virtualization-services-server-2.10-SNAPSHOT-sources.jar
generated-sources  maven-archiver          rat.txt       virtualization-services-server-2.10-SNAPSHOT.jar

2021-05-31 13:37 UTC, gururajrkatti requested changes

2021-05-31 13:37 UTC, gururajrkatti commented on v/virtualization-services-server/virtualization-services-server_ubuntu_20.04.sh
> +# Version       : V2.9
Is it V2.9 (including V) or 2.10 ?

2021-05-31 13:37 UTC, gururajrkatti commented on v/virtualization-services-server/virtualization-services-server_ubuntu_20.04.sh
> +git clone --depth 1 --branch $BRANCH $URL --single-branch
Whats the default branch it will build if we don't pass any args ?

2021-06-04 11:14 UTC, gururajrkatti approved these changes
ok

2021-06-17 03:41 UTC, merged