Generex Build script
ppc64le/build-scripts pull request #920
Opened 2021-05-31 13:20 UTC by dthadi3

2021-05-31 13:22 UTC, dthadi3 commented
[INFO] Installing /Generex/target/generex-1.0.2.jar to /root/.m2/repository/com/github/mifmif/generex/1.0.2/generex-1.0.2.jar
[INFO] Installing /Generex/pom.xml to /root/.m2/repository/com/github/mifmif/generex/1.0.2/generex-1.0.2.pom
[INFO] Installing /Generex/target/generex-1.0.2-javadoc.jar to /root/.m2/repository/com/github/mifmif/generex/1.0.2/generex-1.0.2-javadoc.jar
[INFO] Installing /Generex/target/generex-1.0.2-sources.jar to /root/.m2/repository/com/github/mifmif/generex/1.0.2/generex-1.0.2-sources.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 48.677 s
[INFO] Finished at: 2021-05-31T13:07:02+00:00
[INFO] Final Memory: 54M/415M
[INFO] ------------------------------------------------------------------------
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.github.mifmif:generex:jar:1.0.2
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-javadoc-plugin @ line 212, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-gpg-plugin is missing. @ line 226, column 12
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] Inspecting build with total of 1 modules...
[INFO] Not installing Nexus Staging features:
[INFO]  * Preexisting staging related goal bindings found in 1 modules.
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Generex 1.0.2
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ generex ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ generex ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] skip non existing resourceDirectory /Generex/target/dependency
[INFO] skip non existing resourceDirectory /Generex/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ generex ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ generex ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Generex/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ generex ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ generex ---
[INFO] Surefire report directory: /Generex/target/surefire-reports
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.17/surefire-junit4-2.17.pom
[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.17/surefire-junit4-2.17.pom (3 KB at 3.5 KB/sec)
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-providers/2.17/surefire-providers-2.17.pom
[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-providers/2.17/surefire-providers-2.17.pom (3 KB at 52.8 KB/sec)
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.17/surefire-junit4-2.17.jar
[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.17/surefire-junit4-2.17.jar (63 KB at 826.5 KB/sec)

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.mifmif.common.regex.GenerexIteratorTest
Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.862 sec - in com.mifmif.common.regex.GenerexIteratorTest
Running com.mifmif.common.regex.GenerexRandomTest
Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.068 sec - in com.mifmif.common.regex.GenerexRandomTest
Running com.mifmif.common.regex.GenerexIteratorUnitTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.161 sec - in com.mifmif.common.regex.GenerexIteratorUnitTest
Running com.mifmif.common.regex.GenerexProvidedRandomTest
Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.051 sec - in com.mifmif.common.regex.GenerexProvidedRandomTest
Running com.mifmif.common.regex.GenerexUnitTest
Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.513 sec - in com.mifmif.common.regex.GenerexUnitTest
Running com.mifmif.common.regex.GenerexTest
Tests run: 25, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.213 sec - in com.mifmif.common.regex.GenerexTest

Results :

Tests run: 121, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.758 s
[INFO] Finished at: 2021-05-31T13:07:12+00:00
[INFO] Final Memory: 22M/233M
[INFO] ------------------------------------------------------------------------

2021-05-31 13:30 UTC, gururajrkatti requested changes

2021-05-31 13:30 UTC, gururajrkatti commented on g/Generex/Generex.sh
> +#!/bin/bash
Pl. add the header comments. Refer build-scripts repos for any of the scripts to get the standard comments.

2021-05-31 13:32 UTC, gururajrkatti requested changes

2021-05-31 13:32 UTC, gururajrkatti commented on g/Generex/Generex.sh
> +git checkout ${VERSION}
what if VERSION wrong/git checkout fails ?

2021-05-31 13:33 UTC, gururajrkatti requested changes

2021-05-31 13:33 UTC, gururajrkatti commented on g/Generex/Generex.sh
> +mvn clean install -DskipTests=true -B -V
If "mvn clean install" fails, should we continue with "mvn test" still ?

2021-06-03 13:46 UTC, dthadi3 commented
root@120ce1cb2f4d:/Generex# cd target/
root@120ce1cb2f4d:/Generex/target# ls
apidocs                 classes              generated-classes          java-imports.xml         maven-status
checkstyle-cachefile    cobertura            generex-1.0.2-javadoc.jar  java-unusedcode.xml      pmd.xml
checkstyle-checker.xml  cpd.xml              generex-1.0.2-sources.jar  javadoc-bundle-options   site
checkstyle-header.txt   findBugsExclude.xml  generex-1.0.2.jar          javancss-raw-report.xml  surefire-reports
checkstyle-result.xml   findbugsXml.xml      java-basic.xml             maven-archiver           test-classes

2021-06-03 13:58 UTC, dthadi3 commented
@gururajrkatti please check now.

2021-06-04 06:31 UTC, gururajrkatti approved these changes
ok

2021-06-17 03:40 UTC, merged