Build script for fluent-bit with patches
ppc64le/build-scripts pull request #943
Opened 2021-06-14 18:48 UTC by ManirajDeivendran

Hi,

Delayed response from the community. So publish build script with patches included PR's.
https://github.com/openresty/luajit2/pull/123
https://github.com/openresty/luajit2/pull/124
https://github.com/fluent/fluent-bit/pull/3591

Need to remove, once it's merged into master.

Kindly review.
Thanks

2021-06-17 03:46 UTC, seth-priya commented
@amitsadaphule please review

2021-06-23 06:36 UTC, amitsadaphule requested changes

2021-06-23 06:41 UTC, ManirajDeivendran commented on f/fluent-bit/patches/configure
> +
luajit2 require file "configure" which is copied into luajit2 folder for build with fluent-bit.

2021-06-23 07:02 UTC, ManirajDeivendran commented on f/fluent-bit/patches/libco.patch
> ++  #elif defined(__powerpc64__) && defined(_CALL_ELF) && (_CALL_ELF == 2)
Yes. You're right. Modified the code accordingly.

2021-06-23 07:03 UTC, ManirajDeivendran commented
@amitsadaphule, Updated the review comments. Please provide your comments if any.

2021-06-23 07:46 UTC, amitsadaphule approved these changes
LGTM

2021-06-30 10:32 UTC, merged