AddingBuildScript_ jpam
ppc64le/build-scripts pull request #978
Opened 2021-07-22 07:41 UTC by santosh653

[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ jpam ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. bu                                                                                        ild is platform dependent!
[INFO] Compiling 4 source files to /home/ubuntu/jpam/jpam/target/classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ jp                                                                                        am ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i                                                                                        .e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/ubuntu/jpam/jpam/src/test/resou                                                                                        rces
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ jpam --                                                                                        -
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. bu                                                                                        ild is platform dependent!
[INFO] Compiling 7 source files to /home/ubuntu/jpam/jpam/target/test-classes
[WARNING] /home/ubuntu/jpam/jpam/src/test/java/net/sf/jpam/AbstractPamTest.java:                                                                                         /home/ubuntu/jpam/jpam/src/test/java/net/sf/jpam/AbstractPamTest.java uses unch                                                                                        ecked or unsafe operations.
[WARNING] /home/ubuntu/jpam/jpam/src/test/java/net/sf/jpam/AbstractPamTest.java:                                                                                         Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ jpam ---
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ jpam ---
[INFO] Building jar: /home/ubuntu/jpam/jpam/target/jpam-1.1.jar
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ jpam ---
[INFO] Installing /home/ubuntu/jpam/jpam/target/jpam-1.1.jar to /home/ubuntu/.m2                                                                                        /repository/net/sf/jpam/jpam/1.1/jpam-1.1.jar
[INFO] Installing /home/ubuntu/jpam/jpam/pom.xml to /home/ubuntu/.m2/repository/                                                                                        net/sf/jpam/jpam/1.1/jpam-1.1.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.987 s
[INFO] Finished at: 2021-07-20T09:55:51Z
[INFO] ------------------------------------------------------------------------

2021-07-27 12:26 UTC, gururajrkatti commented
There are too many commits here. Can you pl. squash them.

2021-07-28 10:01 UTC, santosh653 commented
@gururajrkatti Hi Guru, I have squashed all the commits now., Thanks.,

2021-07-30 12:42 UTC, gururajrkatti requested changes

2021-07-30 12:42 UTC, gururajrkatti commented on j/jpam/LICENSE
> +  Apache License
Indentation issue

2021-07-30 12:42 UTC, gururajrkatti commented on j/jpam/jpam_ubuntu_20.04.sh
> +# Version           : master
Pl. mention what is the version tested

2021-08-03 10:21 UTC, santosh653 commented
@gururajrkatti Can you please review this?

2021-08-04 04:29 UTC, gururajrkatti approved these changes
ok

2021-08-04 05:03 UTC, merged